export const GAMEDATA_STRUCTURES = [
    "AbilOrderDisplay",
    "EffectBehavior",
    "Cost",
    "Cooldown",
    "Charge",
    "CostFactor",
    "TargetSorts",
    "Marker",
    "AbilTargetCursorInfo",
    "AbilArmMagazineInfo",
    "AbilCmdButton",
    "AbilBuildInfo",
    "AbilInventoryInfo",
    "AbilLearnInfo",
    "AbilMergeInfo",
    "AbilMorphInfo",
    "AbilMorphSection",
    "AbilPawnInfo",
    "AbilRallyInfo",
    "AbilResearchInfo",
    "AbilReviveCmdButton",
    "AbilReviveInfo",
    "AbilReviveInfoMax",
    "AbilSpecializeInfo",
    "AbilTrainInfo",
    "AbilWarpTrainInfo",
    "EffectWhichUnit",
    "EffectWhichLocation",
    "EffectWhichBehavior",
    "AccumulatorSwitchCase",
    "AccumulatedFixed",
    "AccumulatedUInt32",
    "AccumulatedGameRate",
    "AccumulatedGameTime",
    "EffectWhichPlayer",
    "AchievementTag",
    "ActorRequest",
    "ActorVisibilityShape",
    "ActorEvent",
    "ActorSiteOpsData",
    "ActorModelAspectSet",
    "ActorModelAspect",
    "ActorHostedAttach",
    "AttachQuery",
    "EventDataFootprint",
    "EventDataSound",
    "ActorPhysicsImpactData",
    "ActorRangeAbil",
    "ActorQuadDecoration",
    "ActorSoundLayer",
    "ActorAVPair",
    "ActorActionTerrainSquib",
    "ActorAVCluster",
    "ActorPhysicsData",
    "ActorQuerySubject",
    "ActorQueryResponse",
    "ActorQuerySubjectResponse",
    "ActorSendBasics",
    "ActorDeathBodySquib",
    "ActorCloakTransition",
    "ActorCloakState",
    "ActorCreepHeightClass",
    "ActorCreepRate",
    "ActorDeathData",
    "ActorDeathDataCustom",
    "LookAtTypeInfo",
    "LookAtType",
    "SplatEmitterMaterialInfo",
    "SplatEmitterInitInfo",
    "ActorOverrideBlendTime",
    "ActorOverrideTransitionBlendTime",
    "ActorOverrideModel",
    "ActorProgressStage",
    "ActorHostedDelta",
    "SerpentAggregate",
    "SerpentSegment",
    "ActorStateInfo",
    "ActorBaseline",
    "ActorDeathDataCustomGroup",
    "ActorUnitImpactSoundExtras",
    "DamagePastRemainingHealth",
    "DamageOverInterval",
    "TerrainSquib",
    "TerrainSquibVisual",
    "UnitAbilSound",
    "ErrorOverride",
    "LayerIcon",
    "LayerIconVariation",
    "LayerIconShield",
    "LayerIconShieldVariation",
    "VitalColor",
    "IconVariation",
    "StatusColor",
    "StatusChargeData",
    "StatusHarvesterData",
    "TextTagParameters",
    "UnitKillRank",
    "BankPath",
    "ArtifactRank",
    "ProductReleaseDate",
    "AttachKey",
    "Modification",
    "DeathResponse",
    "AttributeChange",
    "DamageKind",
    "ScoreValueUpdate",
    "UnitResourceRatio",
    "UnitWeaponData",
    "VeterancyLevel",
    "BehaviorFraction",
    "EffectWhichTimeScale",
    "BehaviorDuration",
    "DamageResponse",
    "VitalRegenVitalRemain",
    "PowerStage",
    "AbilReplace",
    "AbilAdd",
    "SpawnInfo",
    "TooltipBlock",
    "TooltipTimeAbilCmd",
    "ButtonCardLayout",
    "CameraZoom",
    "CameraParam",
    "CameraSmooth",
    "CampaignData",
    "MovieConfig",
    "CharacterVariation",
    "UIColorEntry",
    "CommanderUnit",
    "CommanderTalentTree",
    "CommanderMasteryTalent",
    "CommanderAbil",
    "CommanderDifficultyLevel",
    "ConsoleSkinModel",
    "ConversationProductionLevel",
    "ConversationConditionSet",
    "ConversationCondition",
    "ConversationUserValue",
    "ConversationActionSet",
    "ConversationAction",
    "ConversationFacialAnim",
    "ConversationLine",
    "ConversationRunActions",
    "ConversationWait",
    "ConversationJump",
    "ConversationChoice",
    "ConversationGroup",
    "ConversationComment",
    "ConversationStateIndex",
    "ConversationStateInfoText",
    "ConversationStateInfoValue",
    "ConversationStateInfoModel",
    "ConversationStateInfoUpgrade",
    "ConversationStateInfoAbilCmd",
    "ConversationStateVariation",
    "ConversationStateInfoIds",
    "DataCollectionRecord",
    "UpgradeInfoWeapon",
    "DataFieldsPattern",
    "DataTokensPattern",
    "TextureSheetEntry",
    "EffectDamageArea",
    "EffectSearchRevealerParams",
    "EffectEnumArea",
    "EffectMover",
    "EffectMissileBounce",
    "UpgradeEffect",
    "EffectUpgrade",
    "EffectModifyPlayerCost",
    "EffectModifyUnitCost",
    "EffectModifyWeapon",
    "EffectModifyVital",
    "EffectModifyTurret",
    "EffectSwitchCase",
    "EmoticonPackCampaign",
    "FootprintLayer",
    "FootprintShape",
    "FootprintBitSet",
    "DifficultyLevel",
    "AIBuild",
    "Handicap",
    "MapSize",
    "AspectMargin",
    "TeamColor",
    "AIDescription",
    "TriggerLib",
    "TargetFilterResult",
    "BeaconInfo",
    "DamageTypeInfo",
    "AttackTypeInfo",
    "ResourceConvert",
    "MeleePointThreshold",
    "ChallengeCategory",
    "Challenge",
    "SoundQuality",
    "MinimapData",
    "SelectionData",
    "VolumeFade",
    "ReverbRolloff",
    "VolumeThreshold",
    "VolumeRolloff",
    "SoundData",
    "MixRoute",
    "GlobalSoundData",
    "PointModel",
    "CameraShakeAmplitude",
    "CameraShakeFrequency",
    "CameraShakeRotation",
    "ListenerRolloff",
    "UnitSpeedText",
    "WeaponSpeedText",
    "ObjectGroupData",
    "LoadingScreenHelp",
    "LoadingBar",
    "GameCategory",
    "GameModeInfo",
    "DefaultGameVariant",
    "TutorialConfig",
    "HotkeyInfo",
    "ResourceUI",
    "HelpControlCategoryInfo",
    "HelpControlInfo",
    "HelpGameMechanicInfo",
    "AltSoundtrack",
    "CutsceneAssetPath",
    "HerdLevel",
    "HerdNode",
    "HeroAbilCategory",
    "HeroAbil",
    "HeroHeroicAbility",
    "HeroSpecificVO",
    "HeroTalentTree",
    "HeroTalentTier",
    "HeroSpecificIntroVO",
    "HeroLevelScaling",
    "HeroLevelModification",
    "HeroRatings",
    "HeroAITalentBuild",
    "HeroSpecificUI",
    "HeroStatModifier",
    "ItemContainerSlot",
    "FlareInfo",
    "TimeEvent",
    "LightInfo",
    "DirectionalLight",
    "VariationConfig",
    "LightRegionInfo",
    "MissionCategory",
    "LootChoice",
    "AnimFile",
    "AnimAlias",
    "AttachProps",
    "ModelDataEvent",
    "PhysicsMaterialMapping",
    "TextureDeclare",
    "TextureNameAdaption",
    "TextureInfo",
    "TextureExpressionSpec",
    "TextureMatchSpec",
    "ModelVariation",
    "PathingData",
    "MotionPhase",
    "MotionOverlayPhase",
    "MotionOverlay",
    "StartingUnit",
    "UpkeepTax",
    "RequirementNode",
    "RequirementCount",
    "RewardCategory",
    "RewardSpecificUI",
    "GameReplacement",
    "SkinModelGroup",
    "SkinModelMacroRun",
    "SkinPackEntry",
    "SoundAsset",
    "SyncPointRange",
    "SoundAssetTemplate",
    "SoundLocaleFlags",
    "PitchShift",
    "ReverbBalance",
    "SoundtrackCue",
    "SoundtrackMasterLayer",
    "SoundtrackSlaveLayer",
    "SoundtrackSection",
    "TacAbilData",
    "TalentRank",
    "TalentAbilityModification",
    "TalentModification",
    "TargetFindEnumArea",
    "DSPArray",
    "CreepSettings",
    "FoliageSimulationConfig",
    "TerrainDoodad",
    "Fidget",
    "UnitArmorFormula",
    "StockCharge",
    "UnitAbilData",
    "UnitBehaviorData",
    "CardLayout",
    "CardLayoutButton",
    "AddedOnData",
    "UnitEquipment",
    "UnitReviveInfo",
    "AttributePointsInfo",
    "UpgradeEffectTemplate",
    "ValidatorCondition",
    "ValidatorFunction",
    "ValidatorEnumArea",
    "VoiceOverSkin",
    "VoiceOverGroup",
    "VoiceOverLine",
    "VoicePackExampleLine",
    "UserField",
    "UserInstance",
    "UserInstanceField",
    "UserInstanceAbilCmd",
    "UserInstanceActor",
    "UserInstanceColor",
    "UserInstanceCompare",
    "UserInstanceFixed",
    "UserInstanceGameLink",
    "UserInstanceImage",
    "UserInstanceInt",
    "UserInstanceModel",
    "UserInstanceMovie",
    "UserInstanceSound",
    "UserInstanceString",
    "UserInstanceText",
    "UserInstanceUnit",
    "UserInstanceUpgrade",
    "UserInstanceUser",
    "WaterStateDesc",
    "WaterDoodad",
    "UserInstanceField",
    "UserInstanceAbilCmd",
    "UserInstanceActor",
    "UserInstanceColor",
    "UserInstanceCompare",
    "UserInstanceFixed",
    "UserInstanceGameLink",
    "UserInstanceImage",
    "UserInstanceInt",
    "UserInstanceModel",
    "UserInstanceMovie",
    "UserInstanceSound",
    "UserInstanceString",
    "UserInstanceText",
    "UserInstanceUnit",
    "UserInstanceUpgrade",
    "UserInstanceUser",
    "UserField",
    "UserInstance",
    "WaterStateDesc",
    "WaterDoodad",
]

export const GAME_CATALOGS = {
    Abil: ["Abil","AbilProgress","AbilEffect","AbilQueueable","AbilRedirect","AbilArmMagazine","AbilAttack","AbilAugment","AbilAttackModifier","AbilBattery","AbilBeacon","AbilBehavior","AbilBuild","AbilBuildable","AbilEffectInstant","AbilEffectTarget","AbilHarvest","AbilInteract","AbilInventory","AbilLearn","AbilMerge","AbilMergeable","AbilMorph","AbilMorphPlacement","AbilMove","AbilPawn","AbilQueue","AbilRally","AbilRedirectInstant","AbilRedirectTarget","AbilResearch","AbilRevive","AbilSpecialize","AbilStop","AbilTrain","AbilTransport","AbilWarpable","AbilWarpTrain"],
    Accumulator: ["Accumulator","AccumulatorConstant","AccumulatorVitals","AccumulatorDistance","AccumulatorBehavior","AccumulatorAttributePoints","AccumulatorTrackedUnitCount","AccumulatorLevel","AccumulatorAbilLevel","AccumulatorUnitLevel","AccumulatorVeterancyLevel","AccumulatorCargo","AccumulatorEffectAmount","AccumulatorUserData","AccumulatorUnitCustomValue","AccumulatorSwitch","AccumulatorArithmetic","AccumulatorPlayerScoreValue"],
    Achievement: ["Achievement"],
    AchievementTerm: ["AchievementTerm","AchievementTermAbil","AchievementTermAbilInteract","AchievementTermAbilLoad","AchievementTermAbilUse","AchievementTermAchievement","AchievementTermBehavior","AchievementTermBehaviorAbsorbed","AchievementTermBehaviorCount","AchievementTermBehaviorElapsed","AchievementTermBehaviorState","AchievementTermCombine","AchievementTermEffect","AchievementTermEffectAbsorbed","AchievementTermEffectDamaged","AchievementTermEffectDodged","AchievementTermEffectHealed","AchievementTermEffectKilled","AchievementTermEffectUse","AchievementTermGeneric","AchievementTermReplay","AchievementTermScoreValue","AchievementTermTime","AchievementTermUnit","AchievementTermUnitBirth","AchievementTermUnitDeath","AchievementTermUnitKills","AchievementTermUnitRegen","AchievementTermUnitSupplyLoss"],
    Actor: ["Actor","ActorBase","ActorBearings","ActorCamera","ActorModel","ActorModelMaterial","ActorQuad","ActorForce","ActorForceLineSegment","ActorBeam","ActorRange","ActorRegion","ActorSite","ActorSiteOp","ActorSiteOpBase","ActorSound","ActorSplat","ActorAction","ActorActionOverride","ActorArc","ActorBeamSimple","ActorBeamStandard","ActorBlob","ActorCameraModel","ActorCreep","ActorCutscene","ActorDoodad","ActorDoodadPreserver","ActorFoliageFXSpawner","ActorEditorCamera","ActorEditorPoint","ActorEventMacro","ActorEventMacroRunnable","ActorForceBox","ActorForceConeRoundedEnd","ActorForceCylinder","ActorForceSphere","ActorGlobalConfig","ActorOverrides","ActorLight","ActorLightOmni","ActorLightSpot","ActorLightModel","ActorLightOmniModel","ActorLightSpotModel","ActorLookAt","ActorList","ActorListPerPlayer","ActorPortrait","ActorPower","ActorProgress","ActorPropertyCurveSet","ActorQueryResponse","ActorRegionArc","ActorRegionCircle","ActorRegionCombine","ActorRegionGame","ActorRegionPolygon","ActorRegionQuad","ActorRegionWater","ActorScene","ActorSelection","ActorSetQueried","ActorShadow","ActorShield","ActorShieldImpact","ActorSimple","ActorSiteBillboard","ActorSiteMover","ActorSiteOrbiter","ActorSiteRocker","ActorSiteOp2DRotation","ActorSiteOpAction","ActorSiteOpAttach","ActorSiteOpAttachVolume","ActorSiteOpBanker","ActorSiteOpBankerUnit","ActorSiteOpBasic","ActorSiteOpGameCameraFollow","ActorSiteOpDeathMotion","ActorSiteOpDeltaSum","ActorSiteOpEffect","ActorSiteOpForward","ActorSiteOpHeight","ActorSiteOpHigherOfTerrainAndWater","ActorSiteOpHostBearings","ActorSiteOpHostedOffset","ActorSiteOpIncoming","ActorSiteOpLocalOffset","ActorSiteOpOrientAttachPointTo","ActorSiteOpPatch","ActorSiteOpPersistentOffset","ActorSiteOpOrbiter","ActorSiteOpPhysicsImpact","ActorSiteOpRandomPointInCircle","ActorSiteOpRandomPointInCrossbar","ActorSiteOpRandomPointInSphere","ActorSiteOpRotationExplicit","ActorSiteOpRotationRandom","ActorSiteOpRotationVariancer","ActorSiteOpRotator","ActorSiteOpRotationSmooth","ActorSiteOpSelectionOffset","ActorSiteOpSerpentHead","ActorSiteOpSerpentSegment","ActorSiteOpShadow","ActorSiteOpTether","ActorSiteOpTipability","ActorSiteOpTilter","ActorSiteOpUp","ActorSiteOpZ","ActorSiteOpCursor","ActorSiteOpYawLimiter","ActorSiteOpPitchLimiter","ActorSnapshot","ActorStateMonitor","ActorSquib","ActorBatch","ActorTerrain","ActorTerrainDeformer","ActorText","ActorTurret","ActorUnit","ActorUnitRing","ActorMissile","ActorMinimap"],
    ActorSupport: ["ActorSupport"],
    Alert:["AlertUnknown","Alert"],
    ArmyCategory: ["ArmyCategory"],
    ArmyUnit: ["ArmyUnit"],
    ArmyUpgrade: ["ArmyUpgrade"],
    Artifact: ["Artifact"],
    ArtifactSlot: ["ArtifactSlot"],
    AttachMethod: ["AttachMethod","AttachMethodArcTest","AttachMethodBestMatch","AttachMethodFilter","AttachMethodAttachType","AttachMethodIncoming","AttachMethodLeastDeflection","AttachMethodNodeOccupancy","AttachMethodNodeOccupancy2","AttachMethodNumericField","AttachMethodPattern","AttachMethodPortAllocator","AttachMethodProximity","AttachMethodRandom","AttachMethodReduction","AttachMethodVolumesRequery","AttachMethodVolumesTargets","AttachMethodVolumesWeightedPick"],
    BankCondition: ["BankCondition","BankConditionCompare","BankConditionCompareValueCount","BankConditionCompareValueInteger","BankConditionCompareValueString","BankConditionCompareValueSum","BankConditionCombine","BankConditionCurrentMap"],
    Beam: ["Beam","BeamSync","BeamSyncSweeper","BeamAsync","BeamAsyncLinear","BeamAsyncShadow"],
    Behavior: ["Behavior","BehaviorAttackModifier","BehaviorAttribute","BehaviorUnitTracker","BehaviorBuff","BehaviorClickResponse","BehaviorConjoined","BehaviorCreepSource","BehaviorJump","BehaviorPowerSource","BehaviorPowerUser","BehaviorResource","BehaviorReveal","BehaviorSpawn","BehaviorVeterancy","BehaviorWander"],
    Boost: ["Boost"],
    Bundle: ["Bundle"],
    Button: ["Button"],
    Camera: ["Camera"],
    Campaign: ["Campaign"],
    Character: ["Character"],
    Cliff: ["Cliff"],
    CliffMesh: ["CliffMesh"],
    ColorStyle: ["ColorStyle"],
    Commander: ["Commander"],
    Config: ["Config"],
    ConsoleSkin: ["ConsoleSkin"],
    Conversation: ["Conversation"],
    ConversationState: ["ConversationState"],
    Cursor: ["Cursor"],
    DataCollection: ["DataCollection","DataCollectionUnit","DataCollectionUpgrade","DataCollectionAbil"],
    DataCollectionPattern: ["DataCollectionPattern"],
    DecalPack: ["DecalPack"],
    DSP: ["DSP","DSPChorus","DSPCompressor","DSPCustomCompressor","DSPDistortion","DSPEcho","DSPFlange","DSPHighPass","DSPLimiter","DSPLowPass","DSPLowPassSimple","DSPNormalize","DSPOscillator","DSPParamEQ","DSPPitchShift","DSPReverb"],
    Effect: ["Effect","EffectResponse","EffectAddTrackedUnit","EffectClearTrackedUnits","EffectAddTrackedUnits","EffectRemoveTrackedUnit","EffectApplyBehavior","EffectApplyForce","EffectApplyKinetic","EffectCancelOrder","EffectCreateHealer","EffectCreep","EffectCreatePersistent","EffectRandomPointInCircle","EffectCreateUnit","EffectDamage","EffectDestroyHealer","EffectDestroyPersistent","EffectEnumArea","EffectEnumTrackedUnits","EffectEnumMagazine","EffectEnumTransport","EffectEnumInventory","EffectLastTarget","EffectLoadContainer","EffectIssueOrder","EffectLaunchMissile","EffectModifyPlayer","EffectModifyUnit","EffectMorph","EffectRedirectMissile","EffectReleaseMagazine","EffectRemoveBehavior","EffectRemoveKinetic","EffectReturnMagazine","EffectSet","EffectSwitch","EffectTeleport","EffectTransferBehavior","EffectUseCalldown","EffectUseMagazine","EffectUserData"],
    Emoticon: ["Emoticon"],
    EmoticonPack: ["EmoticonPack"],
    Error: ["Error"],
    Footprint: ["Footprint"],
    FoW: ["FoW"],
    Game: ["Game"],
    GameUI: ["GameUI"],
    Herd: ["Herd"],
    HerdNode: ["HerdNode"],
    Hero: ["Hero"],
    HeroAbil: ["HeroAbil"],
    HeroStat: ["HeroStat"],
    Item: ["Item","ItemAbil","ItemAbilPowerUp","ItemEffect","ItemEffectInstant","ItemEffectTarget"],
    ItemClass: ["ItemClass"],
    ItemContainer: ["ItemContainer"],
    Kinetic: ["Kinetic","KineticFollow","KineticRotate","KineticSequence","KineticSet","KineticTranslate","KineticDistance"],
    LensFlareSet: ["LensFlareSet"],
    Light: ["Light"],
    Location: ["Location"],
    Loot: ["Loot","LootSpawn","LootEffect","LootItem","LootSet","LootUnit"],
    Map: ["Map"],
    Model: ["Model","ModelFoliage"],
    Mount: ["Mount"],
    Mover: ["Mover","MoverAvoid","MoverFlock","MoverMissile","MoverNull"],
    Objective: ["Objective"],
    PhysicsMaterial: ["PhysicsMaterial"],
    Ping: ["Ping"],
    PlayerResponse: ["PlayerResponse","PlayerResponseUnit","PlayerResponseUnitDamage","PlayerResponseUnitDeath","PlayerResponseUnitBirth"],
    PortraitPack: ["PortraitPack"],
    Preload: ["Preload","PreloadAsset","PreloadScene","PreloadActor","PreloadConversation","PreloadModel","PreloadSound","PreloadUnit"],
    PremiumMap: ["PremiumMap"],
    Race: ["Race"],
    RaceBannerPack: ["RaceBannerPack"],
    Requirement: ["Requirement"],
    RequirementNode: ["RequirementNode","RequirementGT","RequirementLT","RequirementGTE","RequirementLTE","RequirementEq","RequirementNE","RequirementAnd","RequirementOr","RequirementXor","RequirementNot","RequirementOdd","RequirementDiv","RequirementMod","RequirementMul","RequirementSum","RequirementConst","RequirementAllowAbil","RequirementAllowBehavior","RequirementAllowUnit","RequirementAllowUpgrade","RequirementCountAbil","RequirementCountBehavior","RequirementCountEffect","RequirementCountUnit","RequirementCountUpgrade"],
    Reverb: ["Reverb"],
    Reward: ["Reward","RewardDecal","RewardIcon","RewardModel","RewardPortrait","RewardBadge","RewardPoints","RewardTrophy","RewardEmoticon","RewardVoicePack","RewardPortraitInGame","RewardConsoleSkin","RewardSpray","RewardSprayUseDecal","RewardRaceBanner","RewardStim"],
    ScoreResult: ["ScoreResult","ScoreResultRoot","ScoreResultScore","ScoreResultGraph","ScoreResultPane","ScoreResultBuildOrder","ScoreResultCallouts","ScoreResultExperience","ScoreResultPerformance"],
    ScoreValue: ["ScoreValue","ScoreValueCustom","ScoreValueStandard","ScoreValueConstant","ScoreValueCombine"],
    Shape: ["Shape","ShapeArc","ShapeQuad"],
    Skin: ["Skin"],
    SkinPack: ["SkinPack"],
    Sound: ["Sound"],
    SoundExclusivity: ["SoundExclusivity"],
    SoundMixSnapshot: ["SoundMixSnapshot"],
    Soundtrack: ["Soundtrack"],
    Spray: ["Spray"],
    SprayPack: ["SprayPack"],
    StimPack: ["StimPack"],
    TacCooldown: ["TacCooldown"],
    Tactical: ["Tactical","TacticalOrder","TacticalSet"],
    Talent: ["Talent"],
    TalentProfile: ["TalentProfile"],
    TargetFind: ["TargetFind","TargetFindBestPoint","TargetFindWorkerRallyPoint","TargetFindRallyPoint","TargetFindEnumArea","TargetFindEffect","TargetFindLastAttacker","TargetFindOffset","TargetFindOrder","TargetFindSet"],
    TargetSort: ["TargetSort","TargetSortAlliance","TargetSortAngle","TargetSortBehaviorCount","TargetSortBehaviorDuration","TargetSortChargeCount","TargetSortChargeRegen","TargetSortCooldown","TargetSortDistance","TargetSortField","TargetSortInterruptible","TargetSortMarker","TargetSortPowerSourceLevel","TargetSortPowerUserLevel","TargetSortPriority","TargetSortRandom","TargetSortValidator","TargetSortVeterancy","TargetSortVital","TargetSortVitalFraction"],
    Terrain: ["Terrain"],
    TerrainObject: ["TerrainObject"],
    CliffDoodad: ["CliffDoodad"],
    TerrainTex: ["TerrainTex"],
    Texture: ["Texture"],
    TextureSheet: ["TextureSheet"],
    Tile: ["Tile"],
    Trophy: ["Trophy"],
    Turret: ["Turret"],
    Unit: ["Unit","UnitHero"],
    Upgrade: ["Upgrade"],
    User: ["User"],
    Validator: ["Validator","ValidatorCombine","ValidatorCondition","ValidatorFunction","ValidatorEffect","ValidatorEffectCompare","ValidatorEffectCompareDodged","ValidatorEffectCompareEvaded","ValidatorEffectTreeUserData","ValidatorGameCompareTimeEvent","ValidatorGameCompareTimeOfDay","ValidatorGameCompareTerrain","ValidatorGameCommanderActive","ValidatorLocation","ValidatorLocationCompareCliffLevel","ValidatorLocationComparePower","ValidatorLocationCompareRange","ValidatorLocationArc","ValidatorLocationCreep","ValidatorLocationCrossChasm","ValidatorLocationCrossCliff","ValidatorLocationEnumArea","ValidatorLocationPathable","ValidatorLocationInPlayableMapArea","ValidatorLocationPlacement","ValidatorLocationShrub","ValidatorLocationType","ValidatorLocationVision","ValidatorPlayer","ValidatorPlayerAlliance","ValidatorPlayerRequirement","ValidatorPlayerTalent","ValidatorPlayerFood","ValidatorPlayerCompare","ValidatorPlayerCompareDifficulty","ValidatorPlayerCompareFoodAvailable","ValidatorPlayerCompareFoodMade","ValidatorPlayerCompareFoodUsed","ValidatorPlayerCompareRace","ValidatorPlayerCompareResource","ValidatorPlayerCompareResult","ValidatorPlayerCompareType","ValidatorUnit","ValidatorUnitInWeaponRange","ValidatorUnitAI","ValidatorUnitCombatAI","ValidatorUnitAlliance","ValidatorUnitAbil","ValidatorUnitBehaviorStackAlias","ValidatorUnitBehaviorState","ValidatorUnitState","ValidatorUnitDetected","ValidatorUnitArmor","ValidatorUnitFilters","ValidatorUnitFlying","ValidatorUnitInventory","ValidatorUnitInventoryIsFull","ValidatorUnitInventoryContainsItem","ValidatorUnitLastDamagePlayer","ValidatorUnitKinetic","ValidatorUnitMissileNullified","ValidatorUnitMover","ValidatorUnitOrder","ValidatorUnitOrderQueue","ValidatorUnitOrderTargetPathable","ValidatorUnitOrderTargetType","ValidatorUnitPathable","ValidatorUnitPathing","ValidatorUnitScanning","ValidatorUnitType","ValidatorUnitWeaponAnimating","ValidatorUnitWeaponFiring","ValidatorUnitWeaponPlane","ValidatorUnitTestWeaponType","ValidatorUnitCompare","ValidatorUnitCompareAIAreaEvalRatio","ValidatorUnitCompareAbilLevel","ValidatorUnitCompareAbilSkillPoint","ValidatorUnitCompareAbilStage","ValidatorUnitCompareAttackPriority","ValidatorUnitCompareBehaviorCount","ValidatorUnitCompareCargo","ValidatorUnitCompareChargeUsed","ValidatorUnitCompareCooldown","ValidatorUnitCompareDamageDealtTime","ValidatorUnitCompareDamageTakenTime","ValidatorUnitCompareDeath","ValidatorUnitCompareDetectRange","ValidatorUnitCompareField","ValidatorUnitCompareKillCount","ValidatorUnitCompareMarkerCount","ValidatorUnitCompareMoverPhase","ValidatorUnitCompareOrderCount","ValidatorUnitCompareOrderTargetRange","ValidatorUnitComparePowerSourceLevel","ValidatorUnitComparePowerUserLevel","ValidatorUnitCompareRallyPointCount","ValidatorUnitCompareResourceContents","ValidatorUnitCompareResourceHarvesters","ValidatorUnitCompareSpeed","ValidatorUnitCompareVeterancyLevel","ValidatorUnitCompareVital","ValidatorUnitCompareVitality","ValidatorUnitCompareHeight","ValidatorCompareTrackedUnitsCount","ValidatorIsUnitTracked"],
    VoiceOver: ["VoiceOver"],
    VoicePack: ["VoicePack"],
    WarChest: ["WarChest"],
    WarChestSeason: ["WarChestSeason"],
    Water: ["Water"],
    Weapon: ["Weapon","WeaponLegacy","WeaponStrafe"]
}
export const CGAME_CATALOGS = {}
for(let cat in GAME_CATALOGS){
    CGAME_CATALOGS["C" + cat] = GAME_CATALOGS[cat].map(c => "C"+c)
}

export const GAME_NAMESPACES = Object.keys(GAME_CATALOGS)

export const GAME_CLASSES = Object.values(GAME_CATALOGS).flat();
export const CGAME_CLASSES = GAME_CLASSES.map(c => "C" + c)
export const SGAMEDATA_STRUCTURES = GAMEDATA_STRUCTURES.map(c => "S" + c)

export const GAME_LOCALES = ["deDE","enUS","esES","esMX","frFR","itIT","koKR","plPL","ptBR","ruRU","zhCN","zhTW"] 
export const GAME_TYPES = [
    "CString",
    "CString4",
    "CString32",
    "CString50",
    "CString80",
    "CReals",
    "CInts",
    "CWords",

    "CDataEntryPath",
    "CWord",
    "CString",
    "CString4",
    "CString32",
    "CString50",
    "CString80",
    "CReals",
    "CInts",
    "CWords",
    "CScaleVector",
    "C3Vector",
    "C2Vector",
    "C2iVector",
    "C2fVector",
    "C4Vector",
    "C3fVector",
    "CDescPath",
    "CAbilSetId",
    "CTargetFilters",
    "CFangleArc",
    "CGameTime",
    "CCmdResult",
    "CfRange",
    "CFangle",
    "CGamePoint",
    "CIdentifier",
    "CColor",
    "CActorKey",
    "CActorTerms",
    "CActorCreateKey",
    "CActorLabelKey",
    "CQuad",
    "CRange",
    "CVariatorActorReal32",
    "CRefKey",
    "CActorAngle",
    "CAnimNameKey",
    "CAnimProps",
    "CFacing",
    "CVariatorActorAngle",
    "CColorHDR",
    "CVariatorActorFangle",
    "CFangleRate",
    "CActorTableKeys1x3",
    "CGameRate",
    "CColorRGB",
    "CUserReference",
    "CAttachKeys",
    "CRect",
    "CiRange",
    "CEffectOffset",
    "CiQuad",
    "CGameSpeed",
    "CVariatorGameFangle",
    "CVariatorGameFixed",
    "CTimeOfDay",
    "CStyleName",
    "CTextureProps",
    "CfQuad",
    "CPitchRange",
    "CVolumeRange",
    "CVolume",
    "CTextureSlot",
    "CGameAcceleration",
    "CActorMsgPayloadPtr",
    "CActorSiteOps",
    "CLabelExpression",
    "CIdSetPlayers",
    "CIdSetTeams",
    "CSubNameKey",
    "CAttachMethods",
    "CActorClassFilters",
    "CActorDeathMembers",
    "CGamePoInt3D",
    "CCatalogReference",
    "CTextureExpression",
    "CMissileAcceleration",
    "CMissileSpeed",
    "CPhaseOutro",
    "CThrowBand",
    "CYawPitchRoll",
    "CFangleRateMissile",
    "CFangleAccelMissile",
    "CPitch",
    "CFourCC",
    "CCardId",
    "TCooldownLink",
    "TChargeLink",
    "TMarkerLink",
    "TPowerLink",
    "TProductHyperlinkId",
    "THyperlinkId",
    "TCatalogFieldPath",
    "TEditorCategories",
    "TGalaxyFunction",
    "TCargoSize",
    "TCargoCapacity",
    "TMarkerCount",
    "TPreemptLevel",
    "TAbilCmdIndex",
    "TCliffLevel",
    "TBattleProductId",
    "TPowerLevel",
    "TConversationItemId",
    "TTechAlias",
    "TDifficultyLevel",
    "TAIBuild",
    "TPlayerId",
    "TMountCategory",
    "TBattleLicenseName",
    "TAttackTargetPriority",
    "TUnitRadius",
    "TUserFieldId",
    "TUserInstanceId",
    "TAttachPropIndex",
    "TCommanderLevel",
    "TConversationStateOpId",
    "TConversationStateIndexId",
    "TConversationStateVariation",
    "TConversationTag",
    "TConversationStateInfoId",
    "TUpgradeEffectValue",
    "TFootprintOffsets",
    "TFootprintBorders",
    "THandicap",
    "TTriggerLibId",
    "TCmdResult",
    "TDifficulty",
    "TSoundWeight",
    "TSoundBalance",
    "TVoiceOverSkinId",
    "TVoiceOverGroupId",
    "TLocaleId",

    "SGameContentCreationData",

    "CTexturePath",
    "CImagePath",


    "CUnitLink",
    "CValidatorLink",
    "CAlertLink",
    "CEffectLink",
    "CButtonLink",
    "CAbilLink",
    "CMoverLink",
    "CTargetSortLink",
    "CCursorLink",
    "CItemContainerLink",
    "CItemClassLink",
    "CUpgradeLink",
    "CAccumulatorLink",
    "CScoreValueLink",
    "CRewardLink",
    "CRaceLink",
    "CAchievementTermLink",
    "CAchievementLink",
    "CPreloadLink",
    "CCameraLink",
    "CModelLink",
    "CWeaponLink",
    "CSoundLink",
    "CBeamLink",
    "CTerrainLink",
    "CFootprintLink",
    "CActorLink",
    "CHerdNodeLink",
    "CArmyUnitLink",
    "CArmyUpgradeLink",
    "CSkinLink",
    "CTalentLink",
    "CItemLink",
    "CPlayerResponseLink",
    "CBankConditionLink",
    "CBoostLink",
    "CCliffMeshLink",
    "CCampaignLink",
    "CConsoleSkinLink",
    "CDataCollectionLink",
    "CCommanderLink",
    "CConversationStateLink",
    "CCharacterLink",
    "CDataCollectionPatternLink",
    "CKineticLink",
    "CEmoticonLink",
    "CBundleLink",
    "CScoreResultLink",
    "CSoundtrackLink",
    "CDSPLink",
    "CHeroStatLink",
    "CMountLink",
    "CTalentProfileLink",
    "CMapLink",
    "CBehaviorLink",
    "CArmyCategoryLink",
    "CLocationLink",
    "CObjectiveLink",
    "CLightLink",
    "CPhysicsMaterialLink",
    "CConversationLink",
    "CRequirementLink",
    "CRequirementNodeLink",
    "CHeroLink",
    "CDecalPackLink",
    "CTextureLink",
    "CSprayLink",
    "CPortraitPackLink",
    "CTrophyLink",
    "CVoicePackLink",
    "CRaceBannerPackLink",
    "CStimPackLink",
    "CSoundExclusivityLink",
    "CSoundMixSnapshotLink",
    "CTargetFindLink",
    "CTacticalLink",
    "CReverbLink",
    "CTerrainTexLink",
    "CTileLink",
    "CCliffLink",
    "CTurretLink",
    "CLootLink",
    "CUserLink",
    "CShapeLink",
    "CTextureSheetLink",
    "CHeroAbilLink",
    "CStringLink",
    "CHotkeyLink",
    "CAssetLink",
    "CBankLink"
]

export const cns = GAME_NAMESPACES.reduce((acc, name) => {acc[name] = "EClassIdC" + name; return acc;}, {});

//make class - namespace associations out of GameCatalog Enum
export const C_NAMESPACES = {}
for(let catalog in GAME_CATALOGS){
    for(let className of GAME_CATALOGS[catalog]){
        C_NAMESPACES["C"+ className] = catalog;
    }
}
C_NAMESPACES