
import {Assets as A, Links as L,   Int, Real,    CReals,     CWord, CString} from "./types.js"
import {SCSchema} from "./schema.js"




export const LAnchor = {
    side: CString,
    relative: CString,
    pos: CString,
    offset: CString,
}

export const LShortcut = {
    val: CString,
    priority: CString,
}

export const LRenderPriority = {
    val: CString
}

export const LCoords = {
    top:     Real,
    left:    Real,
    bottom:  Real,
    right:   Real,
}
export const LEvent = {
        event: CString,
        action:CString,
        frame: CString,
    }


export const LController = {
        stateGroup:  CString,
        dimension:  CString,
        relative:  CString,
        side:  CString,
        type:  CString,
        end:   CString,
        frame: CString,
        Key:   [{type: CString,time: Real, sound: CString}],
        type:  CString,
        time:  CString,
        event: CString,
        property: CString
    }
export const LAnimation = {


    name: CWord,
    Event: [LEvent],
    Controller: [LController]
}


export const LConstant = {
    name:CString,
    val:CString,
    A: CString, B: CString
}

export const LAction = {
    Toggled: CString,
    group: CString,
    state: CString,
    Layer: CString,
    LayerAlpha: CString,
    TextureCoords: CString,
    Texture: CString,
    Camera: CString,
        visible:CString,
    type: CString,
    frame:CString,
    DesaturationColor: CString,
    Desaturated: CString,
    ColorAdjustMode: CString,
    LightAdjustColor:CString,
    DarkAdjustColor:CString,
    LayerVisible:   CString,
    on:CString,
    A: CString,
    Texture:A.Image,
    event: CString,
    undo: CString,
    Visible: CString,
    side: CString,
    pos: CString,
    relative: CString,
    offset: CString,
    UnitWorldZ: CString,
    Color: CString,
}

export const LWhen = {
        Hovering: CString,
        Toggled: CString,
        Alpha: CString,
        PowerState: CString,
        Visible: CString,
        ObserverUIState: CString,
        UnitStatusValidatorState: CString,
        type: CString,
        frame: CString,
        operator: CString,
        Text: CString,
        Texture: A.Image,
        UseClassicIcons:  CString,
        ClassicIcon:  CString,
        Desaturated: CString,
        DesaturationColor:  CString,
        Enabled:  CString,
        ClassicIconRacialTint:  CString,
        ClassicIconState: CString,
        IsBWRace:  CString,
        UnitLink:  CString,
        A:  CString,
        CurrentValue:  CString,
        Action: [LAction],
}
export const LState = {
    name: CString,
    Action:[LAction],
    When: [LWhen]
}
export const LStateGroup = {
    name: {
        value: CString
    },
    DefaultState : {
        val: CString
    },
    State: [LState],
    template: {
       value:CString
    },
}

export const LTexture = { val: CString, layer : Int }
export const LTextureType = {  val: CString,layer: CString }
export const LFrame = {
    type: CString,
    name: CString,
    file: CString,
    AutoSizeClamps: {maxWidth: Int, minHeight: Int, minWidth: Int, maxHeight: Int},
    Height:   [{ val: CString }],
    Width:   [{ val: CString }],
    Style :   [{ val: CString }],
    Enabled :   [{ val: CString }],
    Text:  [{ val: CString }],
    template: CString,
    Visible: [{ val: CString }],
    Anchor: [LAnchor],
    Shortcut: [LShortcut],
    RenderPriority: LRenderPriority,
    Handle: {val: CString},
    Texture: [LTexture],
    TextureCoords: [LCoords],
    FormatText: [{ val: CString }],
    Replacement: [{ val: CString }],
    Hotkey: [{ val: CString }],
    DescFlags: [{ val: CString }],
    Color: [{ val: CString }],
    DesaturateOnDisable: [{ val: CString }],
    Alpha: [{ val: CString }],
    SubpixelRendering: [{ val: CString }],
    AcceptsMouse: [{ val: CString }],
    SnapToDevicePixels: [{ val: CString }],
    CollapseLayout: [{ val: CString }],
    Constant: [LConstant],
    Operator: [{ val: CString }],
    TextureType: [LTextureType],
    Rotation: [{ val: CString }],
    IgnoreParentAlpha: [{ val: CString }],
    ClicksOn: [{ val: CString }],
    Toggleable: [{ val: CString }],
    Toggled: [{ val: CString }],
    Animation : [LAnimation],
    StateGroup: [LStateGroup],
    TooltipAnchorPosition: [{ val: CString }],
    StartValue: [{ val: CString }],
    CurrentValue: [{ val: CString }],
    RenderType: [{ val: CString }],
    Behavior: { val: L.Behavior },
    HideMax: [{ val: CString }],
    StackFormatString: [{ val: CString }],
    MinValue: [{ val: CString }],
    MaxValue: [{ val: CString }],
    Value: [{ val: CString }],
    UseSelectionLeader: [{ val: CString }],
    UnitTag: [{ val: CString }],
    UseAlternateTime: [{ val: CString }],
    CountdownTime: [{ val: CString }],
    TargetValue: [{ val: CString }],
    AdjustmentColor: [{ val: CString }],
    ColorAdjustMode: [{ val: CString }],
    Desaturated: [{ val: CString }],
    DesaturationColor: [{ val: CString }],
    AutoPlay: [{ val: CString }],
    File: [{ val: CString }],
    Fading: [{ val: CString }],
    Tooltip: [{ val: CString }],
    DesaturateOnDisable: [{ val: CString }],
    TabListItem: [{ val: CString }],
    PanelListItem: [{ val: CString }],
    RequiredDefines: [{ val: CString }],
    DragCursor: [{ val: CString }],
    DragHoverCursor: [{ val: CString }],
    Draggable: [{ val: CString }],
    DragConstraintFrame: [{ val: CString }],
    Muted: [{ val: CString }],
    NormalImage: [{ val: CString }],
    HoverImage: [{ val: CString }],
    Unclipped: [{ val: CString }],
    LayerColor: [{ val: CString }],
    LayerCount: [{ val: CString }],
    Color: [{ val: CString }],
    URL: [{ val: CString }],
    DescFlags: [{ val: CString }],
    SubpixelRendering: [{ val: CString }],
    PreserveAnchorOffset: [{ val: CString }],
    A: [{ val: CString }],
    B: [{ val: CString }],
    Operator: [{ val: CString }],
    Validator: [{ val: CString }],
    SnapToDevicePixels: [{ val: CString }],
    SegmentValue: [{ val: CString }],
    BarInsetRect:  LCoords,
    BackgroundInsetRect:  LCoords,
    BackgroundShown: [{ val: CString }],
    BackgroundColor: [{ val: CString }],
    OwnerColor: [{ val: CString }],
    AllyColor: [{ val: CString }],
    EnemyColor: [{ val: CString }],
    ReductionColor: [{ val: CString }],
    ReductionShown: [{ val: CString }],
    IncreaseDuration: [{ val: CString }],
    DecreaseDuration: [{ val: CString }],
    Segmented: [{ val: CString }],
    BarCount: [{ val: CString }],
    OwnerRenderPriority: [{ val: CString }],
    AllyRenderPriority: [{ val: CString }],
    EnemyRenderPriority: [{ val: CString }],
    RejectsFocus: [{ val: CString }],
    MaxCharacters: [{ val: CString }],
    UseFillContainer: [{ val: CString }],
    AcceptsMouseTooltip: [{ val: CString }],
    ShowOnDefeat: [{ val: CString }],
    HitTestFrame: [{ val: CString }],
    TooltipFrame: [{ val: CString }],
    ClickSound: [{ val: CString }],
    HoverSound: [{ val: CString }],
    DisplayType: [{ val: CString }],
    AlphaMaskTexture: [{ val: CString }],
    AlphaMaskSiblings: [{ val: CString }],
    ConsoleWorldTopOffset: [{ val: CString }],
    ConsoleWorldBottomOffset: [{ val: CString }],
    VisibleToEnemy: [{ val: CString }],
    VisibleToAlly: [{ val: CString }],
    Batch: [{ val: CString }],
    
    Image: [{ val: CString }],
    Button: [{ val: CString }],
    Orientation: [{ val: CString }],
    ItemHeight: [{ val: CString }],
    ItemGap: [{ val: CString }],
    Insets: [{ val: CString }],
    HighlightInsets: [{ val: CString }],
    HighlightOnHover: [{ val: CString }],
    ItemDesc: [{ val: CString }],
    DisabledAlpha: [{ val: CString }],
    HighlightColor: [{ val: CString }],
    HighlightAlpha: [{ val: CString }],
    Options: [{ val: CString }],
    LayerVisible: [{ val: CString }],
    Tiled: [{ val: CString }],
    StateCount: [{ val: CString }],
    Label: [{ val: CString }],
    DisabledAlpha: [{ val: CString }],
    CheckImage: [{ val: CString }],
    CheckSound: [{ val: CString }],
    DisabledAlpha: [{ val: CString }],
    FillContainer: [{ val: CString }],
    FillBarImage: [{ val: CString }],
    AutoSizeFillBar: [{ val: CString }],
    IncrementSound: [{ val: CString }],
    BackgroundImage: [{ val: CString }],
    SelectedImage: [{ val: CString }],
    ScrollBar: [{ val: CString }],
    ItemClickSound: [{ val: CString }],
    ArrowImage: [{ val: CString }],
    ArrowHoverImage: [{ val: CString }],
    ItemContainer: [{ val: CString }],
    Menu: [{ val: CString }],
    MenuShownSound: [{ val: CString }],
    MenuHiddenSound: [{ val: CString }],
    MenuMinWidth: [{ val: CString }],
    ItemHeight: [{ val: CString }],
    Insets: [{ val: CString }],
    HighlightInsets: [{ val: CString }],
    BackgroundImage: [{ val: CString }],
    SelectedImage: [{ val: CString }],
    ScrollBar: [{ val: CString }],
    HighlightOnHover: [{ val: CString }],
    ItemClickSound: [{ val: CString }],
    ItemDesc: [{ val: CString }],
    DefaultIcon: [{ val: CString }],
    FolderIcon: [{ val: CString }],
    UpIcon: [{ val: CString }],
    UpString: [{ val: CString }],
    ItemIndent: [{ val: CString }],
    MaxLength: [{ val: CString }],
    AnimDuration: [{ val: CString }],
    AnimColumns: [{ val: CString }],
    AnimCount: [{ val: CString }],
    Animating: [{ val: CString }],
    ManagedAnim: [{ val: CString }],
    PausedImage: [{ val: CString }],
    ProgressSlider: [{ val: CString }],
    BufferingImage: [{ val: CString }],
    AnimDuration: [{ val: CString }],
    Continuous: [{ val: CString }],
    Orientation: [{ val: CString }],
    FillContainer: [{ val: CString }],
    FillBarImage: [{ val: CString }],
    FillBar2Image: [{ val: CString }],
    StreamingAllowed: [{ val: CString }],
    MaxMessages: [{ val: CString }],
    MessageDuration: [{ val: CString }],
    FadeDuration: [{ val: CString }],
    BatchText: [{ val: CString }],
    BlendMode: [{ val: CString }],
    AlphaLayer: [{ val: CString }],
    MaxWidth: [{ val: CString }],
    MinWidth: [{ val: CString }],
    PresenceId: [{ val: CString }],
    AchievementId: [{ val: CString }],
    Options: [{ val: CString }],
    HookupAlias: [{ val: CString }],
    Address: [{ val: CString }],
    BlocksShortcuts: [{ val: CString }],
    StepValue: [{ val: CString }],
    Continuous: [{ val: CString }],
    WrapUV: [{ val: CString }],

    LayerAlpha: [{ val: CString }],
    BlurAmount: [{ val: CString }],
    MinVisibleAspectRatio: [{ val: CString }],
    HighlightImage: [{ val: CString }],
    CompositionLabel: [{ val: CString }],
    ReadingLabel: [{ val: CString }],
    LanguageLabel: [{ val: CString }],
    ClickOnContextMenu: [{ val: CString }],
    AllowPageWrap: [{ val: CString }],
    AllowAutoPageWrap: [{ val: CString }],
    AutoIncrement: [{ val: CString }],
    CycleDelay: [{ val: CString }],
    FillInset: [{ val: CString }],
    SaveScrollHeightOnClear: [{ val: CString }],
    AlphaChannel: [{ val: CString }],
    LoseFocusOnEnterOrEsc: [{ val: CString }],
    MenuGap: [{ val: CString }],
    Blur: [{ val: CString }],
    ClubId: [{ val: CString }],
    SelectedSound: [{ val: CString }],
    HideWhenCleared: [{ val: CString }],
    MultiLine: [{ val: CString }],
    LoseFocusOnEsc: [{ val: CString }],
    TextureCoordRotation: [{ val: CString }],
    TurningEnabled: [{ val: CString }],
    Camera: [{ val: CString }],
    UnitWorldX: [{ val: CString }],
    UnitWorldY: [{ val: CString }],
    UnitWorldZ: [{ val: CString }],
    ScaleWidthToTexture: [{ val: CString }],
    UseAspectScaling: [{ val: CString }],
    UnitLink: [{ val: CString }],
    CustomModelLink: [{ val: CString }],
    Skin: [{ val: CString }],
    ModelOffscreen: [{ val: CString }],
    LightLink: [{ val: CString }],
    EffectModel: [{ val: CString }],
    EffectCamera: [{ val: CString }],
    LoopingAnim: [{ val: CString }],
    LightAdjustColor: [{ val: CString }],
    Time: [{ val: CString }],
    Time: [{ val: CString }],
    TextureCoordRotation: [{ val: CString }],
    ScaleHeightToTexture: [{ val: CString }],
    GameContent: [{ val: CString }],
    FadeTime: [{ val: CString }],
    Season: [{ val: CString }],
    Round: [{ val: CString }],
    Tier: [{ val: CString }],
    RewardGroup: [{ val: CString }],
    FormatNumber: [{ val: CString }],
    Bundle: [{ val: CString }],
    UpperHeight: [{ val: CString }],
    Season: [{ val: CString }],
    LowerWidth: [{ val: CString }],
    UpperWidth: [{ val: CString }],
    Circular: [{ val: CString }],
    CircularStart: [{ val: CString }],
    CircularEndOffset: [{ val: CString }],
    StartAngle: [{ val: CString }],
    EndAngleOffset: [{ val: CString }],
    Blur: [{ val: CString }],
    BlurAmount: [{ val: CString }],
    GameContent: [{ val: CString }],
    StartAngle: [{ val: CString }],
    EndAngleOffset: [{ val: CString }],
    Blur: [{ val: CString }],
    BlurAmount: [{ val: CString }],
    RotationPosition: [{ val: CString }],
    LowerWidth: [{ val: CString }],
    NydusFeature: [{ val: CString }],
    StartAngle: [{ val: CString }],
    EndAngleOffset: [{ val: CString }],
    MaxVisibleAspectRatio: [{ val: CString }],
    Reward: [{ val: CString }],
    Skin: [{ val: CString }],
    MaxItemPerPage: [{ val: CString }],
    FilterRewardType: [{ val: CString }],
    CycleDelay: [{ val: CString }],
    AllowPageWrap: [{ val: CString }],
    AllowAutoPageWrap: [{ val: CString }],
    AutoIncrement: [{ val: CString }],
    HitTestTexture: [{ val: CString }],
    RotationPosition: [{ val: CString }],
    SourceFrame: [{ val: CString }],
    DestFrame: [{ val: CString }],
    Time: [{ val: CString }],
    LightAdjustColor: [{ val: CString }],
    DarkAdjustColor: [{ val: CString }],
    ContextMenu: [{ val: CString }],
    HasItemContextMenu: [{ val: CString }],
    MapHandle: [{ val: CString }],
    ScaleWidthToTexture: [{ val: CString }],
    MapHandle: [{ val: CString }],
    VariantIndex: [{ val: CString }],
    RequireSelection: [{ val: CString }],
    RotationPosition: [{ val: CString }],
    MenuMaxHeight: [{ val: CString }],
    MenuMaxHeight: [{ val: CString }],
    MenuMaxHeight: [{ val: CString }],
    ApplyLanguageRules: [{ val: CString }],
    MultiLine: [{ val: CString }],
    ColorStep: [{ val: CString }],
    ScaleHeightToTexture: [{ val: CString }],
    HighlightOnGainFocus: [{ val: CString }],
    PasswordMode: [{ val: CString }],
    ReportsStats: [{ val: CString }],
    ItemHoverWhileDisabled: [{ val: CString }],
    UseScrollBar: [{ val: CString }],
    HighlightOnFocus: [{ val: CString }],
    Item: [{ val: CString }],
    TurningEnabled: [{ val: CString }],
    UnitLink: [{ val: CString }],
    Camera: [{ val: CString }],
    UseAspectScaling: [{ val: CString }],
    MenuMaxWidth: [{ val: CString }],
    DifficultyIndex: [{ val: CString }],
    EnabledWhileInParty: [{ val: CString }],
    VisibilityOnFade: [{ val: CString }],
    RaceFourCC: [{ val: CString }],
    QueueHandle: [{ val: CString }],
    ShowPrice: [{ val: CString }],
    AlwaysShow: [{ val: CString }],
    ContextMenu: [{ val: CString }],
    EnabledWhileInParty: [{ val: CString }],
    Item: [{ val: CString }],
    ShowPrice: [{ val: CString }],
    ToneMapping: [{ val: CString }],
    CampaignLink: [{ val: CString }],
    HideIfHasAnyLicense: [{ val: CString }],
    TierCount: [{ val: CString }],
    PixelTextureCoords: [{ val: CString }],
    DarkAdjustColor: [{ val: CString }],
    ClubId: [{ val: CString }],
    PixelTextureCoords: [{ val: CString }],
    UseExactName: [{ val: CString }],
    Item: [{ val: CString }],
    LoseFocusOnEnterOrEsc: [{ val: CString }],
    UseChatSessionMembers: [{ val: CString }],
    ClubId: [{ val: CString }],
    ContextMenu: [{ val: CString }],
    ClubId: [{ val: CString }],
    CountdownSound: [{ val: CString }],
    CountdownSound: [{ val: CString }],
    ShowChangePortrait: [{ val: CString }],
    ToonName: [{ val: CString }],
    AvatarIndex: [{ val: CString }],
    EnabledInStarterEdition: [{ val: CString }],
    EnabledDuringRestrictedState: [{ val: CString }],
    RememberToonSelection: [{ val: CString }],
    HideWhenCleared: [{ val: CString }],
    AllowedButtons: [{ val: CString }],
    ClickOnContextMenu: [{ val: CString }],
    BorderImage: [{ val: CString }],
    MovieFrame: [{ val: CString }],
    UseTransition: [{ val: CString }],
    LockAspectRatio: [{ val: CString }],
    BackgroundVisible: [{ val: CString }],
    UseAspectScaling: [{ val: CString }],
    UnitLink: [{ val: CString }],
    UseScrollBar: [{ val: CString }],
    Inverted: [{ val: CString }],
    ScoreValueLink: [{ val: CString }],
    ContextMenuButtons: [{ val: CString }],
    UseAnchors: [{ val: CString }],
    ItemHoverWhileDisabled: [{ val: CString }],
    FormatNumber: [{ val: CString }],
    MaxLevelMastery: [{ val: CString }],
    ShowScrollBarManually: [{ val: CString }],
    LightAdjustColor: [{ val: CString }],
    DarkAdjustColor: [{ val: CString }],
    LightAdjustColor: [{ val: CString }],
    DarkAdjustColor: [{ val: CString }],
    LightAdjustColor: [{ val: CString }],
    ClearSelectionIfNotVisible: [{ val: CString }],
    ClearSelectionIfNotVisible: [{ val: CString }],
    RemainingTimeUnitThreshold: [{ val: CString }],
    Commander: [{ val: CString }],
    PrestigeLevel: [{ val: CString }],
    MaxCommanderPrestigeLevelUnlocked: [{ val: CString }],
    BatchRankAmount: [{ val: CString }],
    PauseAllowed: [{ val: CString }],
    ReportsStats: [{ val: CString }],
    SelectedIndex: [{ val: CString }],
    ColorStep: [{ val: CString }],
    Circular: [{ val: CString }],
    CircularStart: [{ val: CString }],
    CircularEndOffset: [{ val: CString }],
    ImageMaskTexture: [{ val: CString }],
    HasRenderTarget: [{ val: CString }],
    ScaleWithTexCoords: [{ val: CString }],
    MouseInside: [{ val: CString }],
    AlwaysPositionRelativeToScrollBar: [{ val: CString }],
    ItemScrollBarOffset: [{ val: CString }],
    MinVisibleAspectRatio: [{ val: CString }],
    MenuMaxWidth: [{ val: CString }],
    ProvisionalGames: [{ val: CString }],
    QueueHandle: [{ val: CString }],
    Race: [{ val: CString }],
    CurrentXP: [{ val: CString }],
    UpdateWhileHidden: [{ val: CString }],
    AverageValue: [{ val: CString }],
    HasAverage: [{ val: CString }],
    FormatTime: [{ val: CString }],
    AverageType: [{ val: CString }],
    Race: [{ val: CString }],
    SortScoreValueLink: [{ val: CString }],
    HideBanner: [{ val: CString }],
    League: [{ val: CString }],
    LeagueTier: [{ val: CString }],
    ContextMenuButtons: [{ val: CString }],
    UseAnchors: [{ val: CString }],
    FromScoreScreen: [{ val: CString }],
    ReplacementIndex: [{ val: CString }],
    InvalidIndex: [{ val: CString }],
    StateIndex: [{ val: CString }],
    FormatTime: [{ val: CString }],
    MinFractionDigits: [{ val: CString }],
    MaxFractionDigits: [{ val: CString }],
    TickDesc: [{ val: CString }],
    TickInterval: [{ val: CString }],
    Vertical: [{ val: CString }],
    StartOffset: [{ val: CString }],
    EndOffset: [{ val: CString }],
    MinXVisible: [{ val: CString }],
    MinYVisible: [{ val: CString }],
    Filter: [{ val: CString }],
    Checked: [{ val: CString }],
    QueueHandle: [{ val: CString }],
    ScaleHeightToTexture: [{ val: CString }],
    LowerWidth: [{ val: CString }],
    RequireSelection: [{ val: CString }],
    HideBanner: [{ val: CString }],
    UseRealCurrency: [{ val: CString }],
    ShowPurchaseDialog: [{ val: CString }],
    HideUntilValidated: [{ val: CString }],
    ShowPrice: [{ val: CString }],
    SortMethod: [{ val: CString }],
    EmoticonPack: [{ val: CString }],
    ScaleWidthToTexture: [{ val: CString }],
    ScaleHeightToTexture: [{ val: CString }],
    VoicePack: [{ val: CString }],
    VoicePack: [{ val: CString }],
    LineIndex: [{ val: CString }],
    LowerHeight: [{ val: CString }],
    ConsoleSkin: [{ val: CString }],
    HideAllowed: [{ val: CString }],
    SelectedRace: [{ val: CString }],
    ConsoleSkin: [{ val: CString }],
    Unit: [{ val: CString }],
    RelativePropertyName: [{ val: CString }],
    RelativeGameContentPropertyName: [{ val: CString }],
    ScrollStepValue: [{ val: CString }],
    Skin: [{ val: CString }],
    Unit: [{ val: CString }],
    SortMethod: [{ val: CString }],
    GameContent: [{ val: CString }],
    AlwaysShow: [{ val: CString }],
    Bundle: [{ val: CString }],
    UnlockableTag: [{ val: CString }],
    VoicePack: [{ val: CString }],
    VoicePack: [{ val: CString }],
    ScaleWidthToTexture: [{ val: CString }],
    Wrap: [{ val: CString }],
    UseTooltip: [{ val: CString }],
    ScrollStepValue: [{ val: CString }],
    ReplacedName: [{ val: CString }],
    NydusLink: [{ val: CString }],
    Bundle: [{ val: CString }],
    EmoticonPack: [{ val: CString }],
    RewardListIdentifier: [{ val: CString }],
    Campaign: [{ val: CString }],
    Stimpack: [{ val: CString }],
    NydusLink: [{ val: CString }],
    LinkId: [{ val: CString }],
    BypassDialog: [{ val: CString }],
    HideOwned: [{ val: CString }],
    CommanderId: [{ val: CString }],
    CampaignId: [{ val: CString }],
    ScreenSingleMode: [{ val: CString }],
    UseRawCost: [{ val: CString }],
    Hyperlink: [{ val: CString }],
    SeasonId: [{ val: CString }],
    ClearSelectionIfNotVisible: [{ val: CString }],
    MaxItemPerPage: [{ val: CString }],
    AddDummyEntry: [{ val: CString }],
    PopulateLargeTileList: [{ val: CString }],
    UnlockableTagValue: [{ val: CString }],
    UnlockableIndex: [{ val: CString }],
    FilterText: [{ val: CString }],
    UnlockableTag: [{ val: CString }],
    Nydus: [{ val: CString }],
    UseRealCurrency: [{ val: CString }],
    ShowPurchaseDialog: [{ val: CString }],
    HideUntilValidated: [{ val: CString }],
    Circular: [{ val: CString }],
    CircularStart: [{ val: CString }],
    CircularEndOffset: [{ val: CString }],
    Hyperlink: [{ val: CString }],
    Round: [{ val: CString }],
    Tier: [{ val: CString }],
    RewardGroup: [{ val: CString }],
    UnixTime: [{ val: CString }],
    CurrentXP: [{ val: CString }],
    Blur: [{ val: CString }],
    BlurAmount: [{ val: CString }],
    SeasonId: [{ val: CString }],
    AnchorUseDeviceOffset: [{ val: CString }],
    StickyFocus: [{ val: CString }],
    ExternalLinksUseOSBrowser: [{ val: CString }],
    AnchorUseDeviceOffset: [{ val: CString }],
    ScaleHeightToTexture: [{ val: CString }],
    HideLeagueTier: [{ val: CString }],
    HideBanner: [{ val: CString }],
    SendRatingOnSelect: [{ val: CString }],
    ScaleWidthToTexture: [{ val: CString }],
    ImageMaskTexture: [{ val: CString }],
    PauseAllowed: [{ val: CString }],
    MuteBgMusicWhilePlaying: [{ val: CString }],
    FilterMapHandle: [{ val: CString }],
    ShowMapInfo: [{ val: CString }],
    ShowCreateOffline: [{ val: CString }],
    ModHandle: [{ val: CString }],
    AccountId: [{ val: CString }],
    LobbyName: [{ val: CString }],
    AdvertHandle: [{ val: CString }],
    ScrollStepValue: [{ val: CString }],
    MaxItemPerPage: [{ val: CString }],
    ImageMaskTexture: [{ val: CString }],
    ImageMaskTexture: [{ val: CString }],
    BypassOnlineChecks: [{ val: CString }],
    UnixTime: [{ val: CString }],
    SaveScrollHeightOnClear: [{ val: CString }],
    LoseFocusOnEsc: [{ val: CString }],
    ExpansionTag: [{ val: CString }],
    SearchText: [{ val: CString }],
    ExpansionTag: [{ val: CString }],
    UseDefaultVariant: [{ val: CString }],
    PlayMode: [{ val: CString }],
    ReplacedName: [{ val: CString }],
    ModHandle: [{ val: CString }],
    UseHyperLink: [{ val: CString }],
    HyperLinkIndex: [{ val: CString }],
    ShowMapInfo: [{ val: CString }],
    UseLargeImage: [{ val: CString }],
    VisibilityOnFade: [{ val: CString }],
    CategoryId: [{ val: CString }],
    DisplayCount: [{ val: CString }],
    UnlockableTagValue: [{ val: CString }],
    UnlockableIndex: [{ val: CString }],
    MapHandle: [{ val: CString }],
    AcceptsMouseDropTarget: [{ val: CString }],
    Scope: [{ val: CString }],
    NewTeamId: [{ val: CString }],
    HasNewTeam: [{ val: CString }],
    DragSlotFrame: [{ val: CString }],
    EdgeScrollPerSecond: [{ val: CString }],
    EdgeScrollIncrement: [{ val: CString }],
    EdgeScrollDecrement: [{ val: CString }],
    TeamId: [{ val: CString }],
    AcceptsMouseDropTarget: [{ val: CString }],
    ObserverTeam: [{ val: CString }],
    AcceptsMouseDropTarget: [{ val: CString }],
    SelectedTime: [{ val: CString }],
    ReportText: [{ val: CString }],
    TitleText: [{ val: CString }],
    BodyText: [{ val: CString }],
    CreatedTime: [{ val: CString }],
    DescriptionText: [{ val: CString }],
    IsPrivate: [{ val: CString }],
    IsHidden: [{ val: CString }],
    Category: [{ val: CString }],
    Locale: [{ val: CString }],
    IconPath: [{ val: CString }],
    DecalPath: [{ val: CString }],
    SelectedCategory: [{ val: CString }],
    SelectedLocale: [{ val: CString }],
    SettingName: [{ val: CString }],
    IsPM: [{ val: CString }],
    Date: [{ val: CString }],
    StartTime: [{ val: CString }],
    EndTime: [{ val: CString }],
    MaxYears: [{ val: CString }],
    EndOffsetSeconds: [{ val: CString }],
    MinDate: [{ val: CString }],
    MaxDate: [{ val: CString }],
    Date: [{ val: CString }],
    IncludeFeatured: [{ val: CString }],
    IncludeAll: [{ val: CString }],
    InputDelayTimeout: [{ val: CString }],
    FilterQueueId: [{ val: CString }],
    FilterTheirRace: [{ val: CString }],
    FilterMyRace: [{ val: CString }],
    TagString: [{ val: CString }],
    Tag: [{ val: CString }],
    QueueId: [{ val: CString }],
    ColorStep: [{ val: CString }],
    PointsRecurseChildren: [{ val: CString }],
    TooltipDelayedCategoryId: [{ val: CString }],
    ShowcaseIndex: [{ val: CString }],
    SelectionToggleable: [{ val: CString }],
    CategoryId: [{ val: CString }],
    UnlockableHandle: [{ val: CString }],
    CriteriaId: [{ val: CString }],
    ShortDateFormat: [{ val: CString }],
    SelectionToggleable: [{ val: CString }],
    PointsRecurseChildren: [{ val: CString }],
    FilterQueueId: [{ val: CString }],
    League: [{ val: CString }],
    LeagueTier: [{ val: CString }],
    LeagueRank: [{ val: CString }],
    QueueId: [{ val: CString }],
    SortRank: [{ val: CString }],
    QueueId: [{ val: CString }],
    RaceFourCC: [{ val: CString }],
    IsArrangedTeam: [{ val: CString }],
    Rating: [{ val: CString }],
    QueueId: [{ val: CString }],
    QueueHandle: [{ val: CString }],
    PrimaryPresenceId: [{ val: CString }],
    RaceFourCC: [{ val: CString }],
    TeamHash: [{ val: CString }],
    FileTime: [{ val: CString }],
    SeasonId: [{ val: CString }],
    IncludeUnranked: [{ val: CString }],
    RaceId: [{ val: CString }],
    FilterSeason: [{ val: CString }],
    FilterMyRace: [{ val: CString }],
    IncludeUnranked: [{ val: CString }],
    IsSoloQueue: [{ val: CString }],
    Race: [{ val: CString }],
    BucketName: [{ val: CString }],
    SortRating: [{ val: CString }],
    Arcade: [{ val: CString }],
    SettingName: [{ val: CString }],
    MapHandle: [{ val: CString }],
    MapHandle: [{ val: CString }],
    VariantIndex: [{ val: CString }],
    GameSpeed: [{ val: CString }],
    ShowCreateOffline: [{ val: CString }],
    ExpansionTag: [{ val: CString }],
    GameSpeed: [{ val: CString }],
    UseDefaultVariant: [{ val: CString }],
    AdvertHandle: [{ val: CString }],
    AccountId: [{ val: CString }],
    LobbyName: [{ val: CString }],
    TooltipDelayed: [{ val: CString }],
    UseHyperLink: [{ val: CString }],
    HyperLinkIndex: [{ val: CString }],
    Arcade: [{ val: CString }],
    MapHandle: [{ val: CString }],
    IsRanked: [{ val: CString }],
    LastQueueSettingName: [{ val: CString }],
    Version: [{ val: CString }],
    SettingName: [{ val: CString }],
    NydusLink: [{ val: CString }],
    LinkId: [{ val: CString }],
    BypassDialog: [{ val: CString }],
    Nydus: [{ val: CString }],
    HighlightOnGainFocus: [{ val: CString }],
    DisplayForegroundUI: [{ val: CString }],
    MyAddress: [{ val: CString }],
    Region: [{ val: CString }],
    SmartStretch: [{ val: CString }],
    Purpose: [{ val: CString }],
    ToneMapping: [{ val: CString }],
    DisplayBackgroundModel: [{ val: CString }],
    SelectedTabIndex: [{ val: CString }],
    Hyperlink: [{ val: CString }],
    StartupTexture: [{ val: CString }],
    DefaultTexture: [{ val: CString }],
    IgnoreGraphicsQuality: [{ val: CString }],
    Version: [{ val: CString }],
    MasteryVersion: [{ val: CString }],
    EnabledDuringRestrictedState: [{ val: CString }],
    UseCached: [{ val: CString }],
    CycleDelay: [{ val: CString }],
    AutoIncrement: [{ val: CString }],
    AllowAutoPageWrap: [{ val: CString }],
    NydusLink: [{ val: CString }],
    MaxVisibleAspectRatio: [{ val: CString }],
    TooltipDelayed: [{ val: CString }],
    Version: [{ val: CString }],
    IsArcade: [{ val: CString }],
    IsFlash: [{ val: CString }],
    MinVisibleAspectRatio: [{ val: CString }],
    InsertEmoticon: [{ val: CString }],
    SingleLevel: [{ val: CString }],
    HideProfile: [{ val: CString }],
    BypassOnlineChecks: [{ val: CString }],
    FromScoreScreen: [{ val: CString }],
    IsRanked: [{ val: CString }],
    ExpansionLevel: [{ val: CString }],
    HighestLeague: [{ val: CString }],
    HighestLeagueTier: [{ val: CString }],
    HideProfile: [{ val: CString }],
    ShowChangeToonName: [{ val: CString }],
    ShowChangePortrait: [{ val: CString }],
    IsPreviousSeason: [{ val: CString }],
    IsGrandmasterLadder: [{ val: CString }],
    TeamHash: [{ val: CString }],
    TeamRecordId: [{ val: CString }],
    SelectedMapHandle: [{ val: CString }],
    RequiredExpansionLevel: [{ val: CString }],
    Loop: [{ val: CString }],
    LockAspectRatio: [{ val: CString }],
    BackgroundVisible: [{ val: CString }],
    PauseAllowed: [{ val: CString }],
    AllowOpenOnClick: [{ val: CString }],
    ToonEmail: [{ val: CString }],
    RandomizeContent: [{ val: CString }],
    ScaleWidthToTexture: [{ val: CString }],
    ImageMaskTexture: [{ val: CString }],
    UseApm: [{ val: CString }],
    Projection: [{ val: CString }],
    UseShadows: [{ val: CString }],
    WarningTimeSeconds: [{ val: CString }],
    HighlightOnFocus: [{ val: CString }],
    FlashInputEnabled: [{ val: CString }],
    TeamColorIndex: [{ val: CString }],
    ModelLink: [{ val: CString }],
    TeamColorIndex: [{ val: CString }],
    IncrementButton: [{ val: CString }],
    DecrementButton: [{ val: CString }],
    WriteOutText: [{ val: CString }],
    WriteOutTextDuration: [{ val: CString }],
    Sorted: [{ val: CString }],
    ValueChangeSound: [{ val: CString }],
    HighlightOnFocus: [{ val: CString }],
    Camera: [{ val: CString }],
    Projection: [{ val: CString }],
    UseShadows: [{ val: CString }],
    UseStandardCoordinates: [{ val: CString }],
    ShowAgentInventory: [{ val: CString }],
    IconSortMethod: [{ val: CString }],
    FillInset: [{ val: CString }],
    InGame: [{ val: CString }],
    InGame: [{ val: CString }],
    InGame: [{ val: CString }],
    MovieFrame: [{ val: CString }],
    AllowTargeting: [{ val: CString }],
    AllowSelection: [{ val: CString }],
    AllowCameraCentering: [{ val: CString }],
    ShowOnVictory: [{ val: CString }],
    UsedSoundCategories: [{ val: CString }],
    WaitForPlayerResult: [{ val: CString }],
    IgnoreMinimapPings: [{ val: CString }],
    IgnoreEmotes: [{ val: CString }],
    ShowDelay: [{ val: CString }],
    DrawLineToCursor: [{ val: CString }],
    IgnoreWorldPings: [{ val: CString }],
    UseScrollBar: [{ val: CString }],
    MinVisibleAspectRatio: [{ val: CString }],
    HighlightOnFocus: [{ val: CString }],
    MessageArea: [{ val: CString }],
    TopToBottom: [{ val: CString }],
    WriteOutText: [{ val: CString }],
    WriteOutTextDuration: [{ val: CString }],
    HideClippedMessages: [{ val: CString }],
    FlashInputEnabled: [{ val: CString }],
    InsertEmoticon: [{ val: CString }],
    InsertEmoticon: [{ val: CString }],
    BlurAmount: [{ val: CString }],
    DisplayCount: [{ val: CString }],




}
//nested framesA
LFrame.Frame = [LFrame]


export const LDesc = {
    "@": "Desc",
    DescFlags: [{ val: CString }],
    Include: [{path: A.Layout, requiredtoload: CWord}],
    Frame: [LFrame],
    StateGroup: [LStateGroup],
    Constant: [LConstant],
    Animation: [LAnimation]
}

export default {
    Anchor: LAnchor,
    Shortcut: LShortcut,
    RenderPriority: LRenderPriority,
    Coords: LCoords,
    Animation: LAnimation,
    Constant: LConstant,
    Action: LAction,
    State: LState,
    StateGroup: LStateGroup,
    Frame: LFrame,
    Desc: LDesc,
}

SCSchema.Desc = LDesc






