
import { Int, Real} from "../types/numbers.js"
import { CWord, CString} from "../types/types.js"
import A from "../types/files.js"
import L from "../types/links.js"



export const LAnchor = {
    side: CString,
    relative: CString,
    pos: CString,
    offset: CString,
}

export const LShortcut = {
    val: CString,
    priority: CString,
}

export const LRenderPriority = {
    val: CString
}

export const LCoords = {
    top:     Real,
    left:    Real,
    bottom:  Real,
    right:   Real,
    val: Real,
    layer: Int
}
export const LEvent = {
        event: CString,
        action:CString,
        frame: CString,
    }


export const LKey = {
    bookmark: String,
    timeinc: String,
    filter: String,
    frame: String,
    action: String,
    direction: String,
    value: String,
    type: CString,
    time: Real,
     sound: CString,
     event: CString,
     image: CString,
    in: CString,
    inout: CString,
    out: CString,
    text: CString,
}
export const LController = {
    ModelFrameName: String,
    percentage: String,
    SendToScope: String,
    style1: String,
    style2: String,
    name: String,
    animation: String,
    layer:  String,
    sidelock: String,
    curve: String,
    Frame: String,
    stateGroup:  CString,
    dimension:  CString,
    relative:  CString,
    side:  CString,
    type:  CString,
    end:   CString,
    frame: CString,
    Key:   [LKey],
    time:  CString,
    event: CString,
    property: CString,
    relativeFrame: String,
    pos: String,
}
export const LAnimation = {
    speed: String,
    animation: String,
    curve: String,
    Key: String,
    layer: String,
    ModelFrameName: String,
    percentage: String,
    SendToScope: String,
    sidelock: String,
    style1: String,
    style2: String,
    template: String,
    name: CWord,
    Event: [LEvent],
    Controller: [LController]
}


export const LConstant = {
    name:CString,
    val:CString,
    A: CString, B: CString
}

export const LAction = {
    SelectedIndex: String,
    template: String,
    UseAngleCalculation: String,
    CameraAngleDelay: String,
    AcceptsMouse: String,
    Toggled: CString,
    group: CString,
    state: CString,
    Layer: CString,
    LayerAlpha: CString,
    TextureCoords: CString,
    Texture: CString,
    Camera: CString,
        visible:CString,
    type: CString,
    frame:CString,
    DesaturationColor: CString,
    Desaturated: CString,
    ColorAdjustMode: CString,
    LightAdjustColor:CString,
    DarkAdjustColor:CString,
    LayerVisible:   CString,
    on:CString,
    A: CString,
    event: CString,
    undo: CString,
    Visible: CString,
    side: CString,
    pos: CString,
    relative: CString,
    offset: CString,
    UnitWorldZ: CString,
    Color: CString,
}

export const LWhen = {

ScreenScoreState: String,
IsMatchHistory: String,
IsCoopCampaign: String,
IsCustomGame: String,
ExpansionLevel: String,
VariantIsPremium: String,
LobbyName: String,
IsOnlineGame: String,
CanAddParticipant: String,
CanAddObserver: String,
CanAddComputer: String,
WarChestPurchased: String,
WarChestActiveState:  String,
HasPendingSlots: String,
IsTandemValid: String,
IsLocalMember: String,
IsLocalBanned: String,
ArcadeState: String,
ModState: String,
IsPinned: String,
PinCount: String,
IsExtensionMod: String,
HasPremium: String,
ListBoxState: String,
TutorialState: String,

    GamesPlayed: String,
    RaceState: String,
    visible:String,
    FromScoreScreen: String,
    TeamsResolved: String,
    FeaturedType: String,
    IsBookmarked: String,
    UserProfileState: String,
    Suggested: String,
    PositionState: String,
    Focused: String,
        Hovering: CString,
        Toggled: CString,
        Alpha: CString,
        PowerState: CString,
        Visible: CString,
        ObserverUIState: CString,
        UnitStatusValidatorState: CString,
        type: CString,
        frame: CString,
        operator: CString,
        Text: CString,
        Texture: A.Image,
        UseClassicIcons:  CString,
        ClassicIcon:  CString,
        Desaturated: CString,
        DesaturationColor:  CString,
        Enabled:  CString,
        ClassicIconRacialTint:  CString,
        ClassicIconState: CString,
        IsBWRace:  CString,
        UnitLink:  CString,
        A:  CString,
        CurrentValue:  CString,
        Action: [LAction],
        CurrentConsoleSkin: String,
        CurrentApm: String,
}
export const LState = {
    name: CString,
    Action:[LAction],
    When: [LWhen]
}
export const LStateGroup = {
    name: {
        value: CString
    },
    DefaultState : {
        val: CString
    },
    State: [LState],
    template: {
       value:CString
    },
}
const LFrameValueUnknown = [{ layer: Number, val: CString }]
export const LTexture = { val: CString, layer : Int }
export const LTextureType = {  val: CString,layer: CString }
export const LFrame = {
    type: CString,
    name: CString,
    file: CString,
    AutoSizeClamps: { maxWidth: Int, minHeight: Int, minWidth: Int, maxHeight: Int },
    Height: LFrameValueUnknown,
    Width: LFrameValueUnknown,
    Style: LFrameValueUnknown,
    Enabled: LFrameValueUnknown,
    Text: LFrameValueUnknown,
    template: CString,
    Visible: LFrameValueUnknown,
    Anchor: [LAnchor],
    Shortcut: [LShortcut],
    RenderPriority: LRenderPriority,
    Handle: { val: CString },
    Texture: [LTexture],
    TextureCoords: [LCoords],
    FormatText: LFrameValueUnknown,
    Replacement: LFrameValueUnknown,
    Hotkey: LFrameValueUnknown,
    DescFlags: LFrameValueUnknown,
    Color: LFrameValueUnknown,
    DesaturateOnDisable: LFrameValueUnknown,
    Alpha: LFrameValueUnknown,
    SubpixelRendering: LFrameValueUnknown,
    AcceptsMouse: LFrameValueUnknown,
    AcceptsMouseDropTarget: LFrameValueUnknown,
    AddDummyEntry: LFrameValueUnknown,
    SnapToDevicePixels: LFrameValueUnknown,
    CollapseLayout: LFrameValueUnknown,
    Constant: [LConstant],
    Operator: LFrameValueUnknown,
    TextureType: [LTextureType],
    Rotation: LFrameValueUnknown,
    IgnoreParentAlpha: LFrameValueUnknown,
    ClicksOn: LFrameValueUnknown,
    Toggleable: LFrameValueUnknown,
    Toggled: LFrameValueUnknown,
    Animation: [LAnimation],
    StateGroup: [LStateGroup],
    TooltipAnchorPosition: LFrameValueUnknown,
    StartValue: LFrameValueUnknown,
    CurrentValue: LFrameValueUnknown,
    RenderType: LFrameValueUnknown,
    Behavior: { val: L.Behavior },
    HideMax: LFrameValueUnknown,
    StackFormatString: LFrameValueUnknown,
    MinValue: LFrameValueUnknown,
    MaxValue: LFrameValueUnknown,
    Value: LFrameValueUnknown,
    UseSelectionLeader: LFrameValueUnknown,
    UnitTag: LFrameValueUnknown,
    UseAlternateTime: LFrameValueUnknown,
    CountdownTime: LFrameValueUnknown,
    TargetValue: LFrameValueUnknown,
    AdjustmentColor: LFrameValueUnknown,
    ColorAdjustMode: LFrameValueUnknown,
    Desaturated: LFrameValueUnknown,
    DesaturationColor: LFrameValueUnknown,
    AutoPlay: LFrameValueUnknown,
    File: LFrameValueUnknown,
    Fading: LFrameValueUnknown,
    Tooltip: LFrameValueUnknown,
    TabListItem: LFrameValueUnknown,
    PanelListItem: LFrameValueUnknown,
    RequiredDefines: LFrameValueUnknown,
    DragCursor: LFrameValueUnknown,
    DragHoverCursor: LFrameValueUnknown,
    Draggable: LFrameValueUnknown,
    DragConstraintFrame: LFrameValueUnknown,
    Muted: LFrameValueUnknown,
    NormalImage: LFrameValueUnknown,
    HoverImage: LFrameValueUnknown,
    Unclipped: LFrameValueUnknown,
    LayerColor: LFrameValueUnknown,
    LayerCount: LFrameValueUnknown,
    URL: LFrameValueUnknown,
    PreserveAnchorOffset: LFrameValueUnknown,
    A: LFrameValueUnknown,
    B: LFrameValueUnknown,
    Validator: LFrameValueUnknown,
    SegmentValue: LFrameValueUnknown,
    BarInsetRect: LCoords,
    BackgroundInsetRect: LCoords,
    BackgroundShown: LFrameValueUnknown,
    BackgroundColor: LFrameValueUnknown,
    OwnerColor: LFrameValueUnknown,
    AllyColor: LFrameValueUnknown,
    EnemyColor: LFrameValueUnknown,
    ReductionColor: LFrameValueUnknown,
    ReductionShown: LFrameValueUnknown,
    IncreaseDuration: LFrameValueUnknown,
    DecreaseDuration: LFrameValueUnknown,
    Segmented: LFrameValueUnknown,
    BarCount: LFrameValueUnknown,
    OwnerRenderPriority: LFrameValueUnknown,
    AllyRenderPriority: LFrameValueUnknown,
    EnemyRenderPriority: LFrameValueUnknown,
    RejectsFocus: LFrameValueUnknown,
    MaxCharacters: LFrameValueUnknown,
    UseFillContainer: LFrameValueUnknown,
    AcceptsMouseTooltip: LFrameValueUnknown,
    ShowOnDefeat: LFrameValueUnknown,
    HitTestFrame: LFrameValueUnknown,
    TooltipFrame: LFrameValueUnknown,
    ClickSound: LFrameValueUnknown,
    HoverSound: LFrameValueUnknown,
    DisplayType: LFrameValueUnknown,
    AlphaMaskTexture: LFrameValueUnknown,
    AlphaMaskSiblings: LFrameValueUnknown,
    ConsoleWorldTopOffset: LFrameValueUnknown,
    ConsoleWorldBottomOffset: LFrameValueUnknown,
    VisibleToEnemy: LFrameValueUnknown,
    VisibleToAlly: LFrameValueUnknown,
    Batch: LFrameValueUnknown,
    Image: LFrameValueUnknown,
    Button: LFrameValueUnknown,
    Orientation: LFrameValueUnknown,
    ItemHeight: LFrameValueUnknown,
    ItemGap: LFrameValueUnknown,
    Insets: LCoords,
    HighlightInsets: LCoords,
    HighlightOnHover: LFrameValueUnknown,
    ItemDesc: LFrameValueUnknown,
    DisabledAlpha: LFrameValueUnknown,
    HighlightColor: LFrameValueUnknown,
    HighlightAlpha: LFrameValueUnknown,
    Options: LFrameValueUnknown,
    LayerVisible: LFrameValueUnknown,
    Tiled: LFrameValueUnknown,
    StateCount: LFrameValueUnknown,
    Label: LFrameValueUnknown,
    CheckImage: LFrameValueUnknown,
    CheckSound: LFrameValueUnknown,
    FillContainer: LFrameValueUnknown,
    FillBarImage: LFrameValueUnknown,
    AutoSizeFillBar: LFrameValueUnknown,
    IncrementSound: LFrameValueUnknown,
    BackgroundImage: LFrameValueUnknown,
    SelectedImage: LFrameValueUnknown,
    ScrollBar: LFrameValueUnknown,
    ItemClickSound: LFrameValueUnknown,
    ArrowImage: LFrameValueUnknown,
    ArrowHoverImage: LFrameValueUnknown,
    ItemContainer: LFrameValueUnknown,
    Menu: LFrameValueUnknown,
    MenuShownSound: LFrameValueUnknown,
    MenuHiddenSound: LFrameValueUnknown,
    MenuMinWidth: LFrameValueUnknown,
    DefaultIcon: LFrameValueUnknown,
    FolderIcon: LFrameValueUnknown,
    UpIcon: LFrameValueUnknown,
    UpString: LFrameValueUnknown,
    ItemIndent: LFrameValueUnknown,
    MaxLength: LFrameValueUnknown,
    AnimDuration: LFrameValueUnknown,
    AnimColumns: LFrameValueUnknown,
    AnimCount: LFrameValueUnknown,
    Animating: LFrameValueUnknown,
    ManagedAnim: LFrameValueUnknown,
    PausedImage: LFrameValueUnknown,
    ProgressSlider: LFrameValueUnknown,
    BufferingImage: LFrameValueUnknown,
    Continuous: LFrameValueUnknown,
    FillBar2Image: LFrameValueUnknown,
    StreamingAllowed: LFrameValueUnknown,
    MaxMessages: LFrameValueUnknown,
    MessageDuration: LFrameValueUnknown,
    FadeDuration: LFrameValueUnknown,
    BatchText: LFrameValueUnknown,
    BlendMode: LFrameValueUnknown,
    AlphaLayer: LFrameValueUnknown,
    MaxWidth: LFrameValueUnknown,
    MinWidth: LFrameValueUnknown,
    PresenceId: LFrameValueUnknown,
    AchievementId: LFrameValueUnknown,
    HookupAlias: [{original: String, alias: String}],
    Address: LFrameValueUnknown,
    BlocksShortcuts: LFrameValueUnknown,
    StepValue: LFrameValueUnknown,
    WrapUV: LFrameValueUnknown,
    LayerAlpha: LFrameValueUnknown,
    BlurAmount: LFrameValueUnknown,
    MinVisibleAspectRatio: LFrameValueUnknown,
    HighlightImage: LFrameValueUnknown,
    CompositionLabel: LFrameValueUnknown,
    ReadingLabel: LFrameValueUnknown,
    LanguageLabel: LFrameValueUnknown,
    ClickOnContextMenu: LFrameValueUnknown,
    AllowPageWrap: LFrameValueUnknown,
    AllowAutoPageWrap: LFrameValueUnknown,
    AutoIncrement: LFrameValueUnknown,
    CycleDelay: LFrameValueUnknown,
    FillInset: LFrameValueUnknown,
    SaveScrollHeightOnClear: LFrameValueUnknown,
    AlphaChannel: LFrameValueUnknown,
    LoseFocusOnEnterOrEsc: LFrameValueUnknown,
    MenuGap: LFrameValueUnknown,
    ClubId: LFrameValueUnknown,
    SelectedSound: LFrameValueUnknown,
    HideWhenCleared: LFrameValueUnknown,
    MultiLine: LFrameValueUnknown,
    TextureCoordRotation: LFrameValueUnknown,
    TurningEnabled: LFrameValueUnknown,
    Camera: {
        position: String,
        target: String,
        fov: String,
        minz: String,
        maxz: String,
        val: L.Camera
    },
    UnitWorldX: LFrameValueUnknown,
    UnitWorldY: LFrameValueUnknown,
    UnitWorldZ: LFrameValueUnknown,
    ScaleWidthToTexture: LFrameValueUnknown,
    UseAspectScaling: LFrameValueUnknown,
    UnitLink: LFrameValueUnknown,
    CustomModelLink: LFrameValueUnknown,
    Skin: LFrameValueUnknown,
    ModelOffscreen: LFrameValueUnknown,
    LightLink: LFrameValueUnknown,
    EffectModel: LFrameValueUnknown,
    EffectCamera: LFrameValueUnknown,
    LoopingAnim: LFrameValueUnknown,
    LightAdjustColor: LFrameValueUnknown,
    Time: LFrameValueUnknown,
    ScaleHeightToTexture: LFrameValueUnknown,
    GameContent: LFrameValueUnknown,
    FadeTime: LFrameValueUnknown,
    Season: LFrameValueUnknown,
    Round: LFrameValueUnknown,
    Tier: LFrameValueUnknown,
    RewardGroup: LFrameValueUnknown,
    FormatNumber: LFrameValueUnknown,
    Bundle: LFrameValueUnknown,
    UpperHeight: LFrameValueUnknown,
    LowerWidth: LFrameValueUnknown,
    UpperWidth: LFrameValueUnknown,
    Circular: LFrameValueUnknown,
    CircularStart: LFrameValueUnknown,
    CircularEndOffset: LFrameValueUnknown,
    StartAngle: LFrameValueUnknown,
    EndAngleOffset: LFrameValueUnknown,
    RotationPosition: LFrameValueUnknown,
    NydusFeature: LFrameValueUnknown,
    MaxVisibleAspectRatio: LFrameValueUnknown,
    Reward: LFrameValueUnknown,
    MaxItemPerPage: LFrameValueUnknown,
    FilterRewardType: LFrameValueUnknown,
    HitTestTexture: LFrameValueUnknown,
    SourceFrame: LFrameValueUnknown,
    DestFrame: LFrameValueUnknown,
    VariantIndex: LFrameValueUnknown,
    RequireSelection: LFrameValueUnknown,
    MenuMaxHeight: LFrameValueUnknown,
    ApplyLanguageRules: LFrameValueUnknown,
    ColorStep: LFrameValueUnknown,
    PasswordMode: LFrameValueUnknown,
    ReportsStats: LFrameValueUnknown,
    ItemHoverWhileDisabled: LFrameValueUnknown,
    UseScrollBar: LFrameValueUnknown,
    HighlightOnFocus: LFrameValueUnknown,
    Item: LFrameValueUnknown,
    MenuMaxWidth: LFrameValueUnknown,
    DifficultyIndex: LFrameValueUnknown,
    EnabledWhileInParty: LFrameValueUnknown,
    VisibilityOnFade: LFrameValueUnknown,
    RaceFourCC: LFrameValueUnknown,
    QueueHandle: LFrameValueUnknown,
    ShowPrice: LFrameValueUnknown,
    AlwaysShow: LFrameValueUnknown,
    ContextMenu: LFrameValueUnknown,
    ToneMapping: LFrameValueUnknown,
    CampaignLink: LFrameValueUnknown,
    HideIfHasAnyLicense: LFrameValueUnknown,
    TierCount: LFrameValueUnknown,
    PixelTextureCoords: LFrameValueUnknown,
    UseExactName: LFrameValueUnknown,
    UseChatSessionMembers: LFrameValueUnknown,
    CountdownSound: LFrameValueUnknown,
    ShowChangePortrait: LFrameValueUnknown,
    ToonName: LFrameValueUnknown,
    AvatarIndex: LFrameValueUnknown,
    EnabledInStarterEdition: LFrameValueUnknown,
    RememberToonSelection: LFrameValueUnknown,
    AllowedButtons: LFrameValueUnknown,
    BorderImage: LFrameValueUnknown,
    MovieFrame: LFrameValueUnknown,
    UseTransition: LFrameValueUnknown,
    LockAspectRatio: LFrameValueUnknown,
    BackgroundVisible: LFrameValueUnknown,


    Type: String,
    Blur: LFrameValueUnknown,
    HasItemContextMenu: LFrameValueUnknown,
    requiredtoload: String,
    Inverted: LFrameValueUnknown,
    MaxLevelMastery: LFrameValueUnknown,
    RemainingTimeUnitThreshold: LFrameValueUnknown,
    BatchRankAmount: LFrameValueUnknown,
    ProvisionalGames: LFrameValueUnknown,
    CurrentXP: LFrameValueUnknown,
    SortScoreValueLink: LFrameValueUnknown,
    UpdateWhileHidden: LFrameValueUnknown,
    AverageType: LFrameValueUnknown,
    Race: LFrameValueUnknown,
    FormatTime: LFrameValueUnknown,
    MinFractionDigits: LFrameValueUnknown,
    MaxFractionDigits: LFrameValueUnknown,
    ScoreValueLink: LFrameValueUnknown,
    Filter: LFrameValueUnknown,
    UseRealCurrency: LFrameValueUnknown,
    ShowPurchaseDialog: LFrameValueUnknown,
    HideUntilValidated: LFrameValueUnknown,
    SortMethod: LFrameValueUnknown,
    EmoticonPack: LFrameValueUnknown,
    VoicePack: LFrameValueUnknown,
    HideAllowed: LFrameValueUnknown,
    SelectedRace: LFrameValueUnknown,
    Wrap: LFrameValueUnknown,
    UseTooltip: LFrameValueUnknown,
    ScrollStepValue: LFrameValueUnknown,
    RelativePropertyName: LFrameValueUnknown,
    RelativeGameContentPropertyName: LFrameValueUnknown,
    HideOwned: LFrameValueUnknown,
    Hyperlink: LFrameValueUnknown,
    ClearSelectionIfNotVisible: LFrameValueUnknown,
    PopulateLargeTileList: LFrameValueUnknown,
    FilterText: LFrameValueUnknown,
    UnlockableTag: LFrameValueUnknown,
    SearchText: LFrameValueUnknown,
    ExpansionTag: LFrameValueUnknown,
    DragSlotFrame: LFrameValueUnknown,
    MapHandle: LFrameValueUnknown,
    SelectedTime: LFrameValueUnknown,
    DisplayCount: LFrameValueUnknown,
    ReportText: LFrameValueUnknown,
    TitleText: LFrameValueUnknown,
    BodyText: LFrameValueUnknown,
    IsPM: LFrameValueUnknown,
    Date: LFrameValueUnknown,
    StartTime: LFrameValueUnknown,
    EndTime: LFrameValueUnknown,
    MaxYears: LFrameValueUnknown,
    EndOffsetSeconds: LFrameValueUnknown,
    DescriptionText: LFrameValueUnknown,
    IsPrivate: LFrameValueUnknown,
    IsHidden: LFrameValueUnknown,
    Category: LFrameValueUnknown,
    Locale: LFrameValueUnknown,
    IconPath: LFrameValueUnknown,
    DecalPath: LFrameValueUnknown,
    PointsRecurseChildren: LFrameValueUnknown,
    TooltipDelayed: LFrameValueUnknown,
    SelectionToggleable: LFrameValueUnknown,
    CategoryId: LFrameValueUnknown,
    ShortDateFormat: LFrameValueUnknown,
    FilterQueueId: LFrameValueUnknown,
    QueueId: LFrameValueUnknown,
    SortRank: LFrameValueUnknown,
    PrimaryPresenceId: LFrameValueUnknown,
    IncludeUnranked: LFrameValueUnknown,
    BucketName: LFrameValueUnknown,
    SortRating: LFrameValueUnknown,
    Arcade: LFrameValueUnknown,
    IsRanked: LFrameValueUnknown,
    DisplayBackgroundModel: LFrameValueUnknown,
    DisplayForegroundUI: LFrameValueUnknown,
    SelectedTabIndex: LFrameValueUnknown,
    MyAddress: LFrameValueUnknown,
    Region: LFrameValueUnknown,
    StartupTexture: LFrameValueUnknown,
    DefaultTexture: LFrameValueUnknown,
    MasteryVersion: LFrameValueUnknown,
    UseCached: LFrameValueUnknown,
    AllowOpenOnClick: LFrameValueUnknown,
    ToonEmail: LFrameValueUnknown,
    RandomizeContent: LFrameValueUnknown,
    Loop: LFrameValueUnknown,
    PauseAllowed: LFrameValueUnknown,
    UseApm: LFrameValueUnknown,
    WarningTimeSeconds: LFrameValueUnknown,
    TeamColorIndex: LFrameValueUnknown,
    IncrementButton: LFrameValueUnknown,
    DecrementButton: LFrameValueUnknown,
    Sorted: LFrameValueUnknown,
    ShowAgentInventory: LFrameValueUnknown,
    IconSortMethod: LFrameValueUnknown,
    ShowOnVictory: LFrameValueUnknown,
    UsedSoundCategories: LFrameValueUnknown,
    AllowTargeting: LFrameValueUnknown,
    AllowSelection: LFrameValueUnknown,
    AllowCameraCentering: LFrameValueUnknown,
    IgnoreMinimapPings: LFrameValueUnknown,
    IgnoreEmotes: LFrameValueUnknown,
    ShowDelay: LFrameValueUnknown,
    DrawLineToCursor: LFrameValueUnknown,
    IgnoreWorldPings: LFrameValueUnknown,



    LoseFocusOnEsc: LFrameValueUnknown,
    DarkAdjustColor: LFrameValueUnknown,
    EnabledDuringRestrictedState: LFrameValueUnknown,
    ContextMenuButtons: LFrameValueUnknown,
    ShowScrollBarManually: LFrameValueUnknown,
    UseAnchors: LFrameValueUnknown,
    Commander: LFrameValueUnknown,
    PrestigeLevel: LFrameValueUnknown,
    MaxCommanderPrestigeLevelUnlocked: LFrameValueUnknown,
    SelectedIndex: LFrameValueUnknown,
    HasRenderTarget: LFrameValueUnknown,
    ScaleWithTexCoords: LFrameValueUnknown,
    MouseInside: LFrameValueUnknown,
    AlwaysPositionRelativeToScrollBar: LFrameValueUnknown,
    ItemScrollBarOffset: LFrameValueUnknown,
    AverageValue: LFrameValueUnknown,
    HasAverage: LFrameValueUnknown,
    ReplacementIndex: LFrameValueUnknown,
    InvalidIndex: LFrameValueUnknown,
    StateIndex: LFrameValueUnknown,
    TickDesc: LFrameValueUnknown,
    TickInterval: LFrameValueUnknown,
    Vertical: LFrameValueUnknown,
    StartOffset: LFrameValueUnknown,
    EndOffset: LFrameValueUnknown,
    MinXVisible: LFrameValueUnknown,
    MinYVisible: LFrameValueUnknown,
    Checked: LFrameValueUnknown,
    HideBanner: LFrameValueUnknown,
    LineIndex: LFrameValueUnknown,
    ConsoleSkin: LFrameValueUnknown,
    RewardListIdentifier: LFrameValueUnknown,
    Campaign: LFrameValueUnknown,
    Stimpack: LFrameValueUnknown,
    NydusLink: LFrameValueUnknown,
    LinkId: LFrameValueUnknown,
    BypassDialog: LFrameValueUnknown,
    Unit: LFrameValueUnknown,
    CommanderId: LFrameValueUnknown,
    CampaignId: LFrameValueUnknown,
    ScreenSingleMode: LFrameValueUnknown,
    UseRawCost: LFrameValueUnknown,
    SeasonId: LFrameValueUnknown,
    UnlockableTagValue: LFrameValueUnknown,
    UnlockableIndex: LFrameValueUnknown,
    Nydus: LFrameValueUnknown,
    AnchorUseDeviceOffset: LFrameValueUnknown,
    StickyFocus: LFrameValueUnknown,
    ExternalLinksUseOSBrowser: LFrameValueUnknown,
    HideLeagueTier: LFrameValueUnknown,
    SendRatingOnSelect: LFrameValueUnknown,
    FilterMapHandle: LFrameValueUnknown,
    AdvertHandle: LFrameValueUnknown,
    ImageMaskTexture: LFrameValueUnknown,
    BypassOnlineChecks: LFrameValueUnknown,
    UseLargeImage: LFrameValueUnknown,
    ModHandle: LFrameValueUnknown,
    UseHyperLink: LFrameValueUnknown,
    HyperLinkIndex: LFrameValueUnknown,
    ShowMapInfo: LFrameValueUnknown,
    UseDefaultVariant: LFrameValueUnknown,
    PlayMode: LFrameValueUnknown,
    Scope: LFrameValueUnknown,
    NewTeamId: LFrameValueUnknown,
    HasNewTeam: LFrameValueUnknown,
    EdgeScrollPerSecond: LFrameValueUnknown,
    EdgeScrollIncrement: LFrameValueUnknown,
    EdgeScrollDecrement: LFrameValueUnknown,
    CreatedTime: LFrameValueUnknown,
    MinDate: LFrameValueUnknown,
    MaxDate: LFrameValueUnknown,
    SelectedCategory: LFrameValueUnknown,
    SelectedLocale: LFrameValueUnknown,
    SettingName: LFrameValueUnknown,
    IncludeFeatured: LFrameValueUnknown,
    IncludeAll: LFrameValueUnknown,
    InputDelayTimeout: LFrameValueUnknown,
    ShowcaseIndex: LFrameValueUnknown,
    FilterTheirRace: LFrameValueUnknown,
    TagString: LFrameValueUnknown,
    Tag: LFrameValueUnknown,
    League: LFrameValueUnknown,
    LeagueTier: LFrameValueUnknown,
    LeagueRank: LFrameValueUnknown,
    TeamHash: LFrameValueUnknown,
    RaceId: LFrameValueUnknown,
    FilterSeason: LFrameValueUnknown,
    FilterMyRace: LFrameValueUnknown,
    IsSoloQueue: LFrameValueUnknown,
    ShowCreateOffline: LFrameValueUnknown,
    AccountId: LFrameValueUnknown,
    LobbyName: LFrameValueUnknown,
    GameSpeed: LFrameValueUnknown,
    LastQueueSettingName: LFrameValueUnknown,
    HighlightOnGainFocus: LFrameValueUnknown,
    SmartStretch: LFrameValueUnknown,
    Purpose: LFrameValueUnknown,
    IgnoreGraphicsQuality: LFrameValueUnknown,
    Version: LFrameValueUnknown,
    IsFlash: LFrameValueUnknown,
    ExpansionLevel: LFrameValueUnknown,
    HideProfile: LFrameValueUnknown,
    SelectedMapHandle: LFrameValueUnknown,
    RequiredExpansionLevel: LFrameValueUnknown,
    Projection: LFrameValueUnknown,
    UseShadows: LFrameValueUnknown,
    FlashInputEnabled: LFrameValueUnknown,
    ModelLink: LFrameValueUnknown,
    WriteOutText: LFrameValueUnknown,
    WriteOutTextDuration: LFrameValueUnknown,
    ValueChangeSound: LFrameValueUnknown,
    InGame: LFrameValueUnknown,
    WaitForPlayerResult: LFrameValueUnknown,
    


    FromScoreScreen: LFrameValueUnknown,
    LowerHeight: LFrameValueUnknown,
    UnixTime: LFrameValueUnknown,
    ReplacedName: LFrameValueUnknown,
    UnlockableHandle: LFrameValueUnknown,
    CriteriaId: LFrameValueUnknown,
    IsArcade: LFrameValueUnknown,
    Name: String,
    InsertEmoticon: LFrameValueUnknown,
    SingleLevel: LFrameValueUnknown,
    HighestLeague: LFrameValueUnknown,
    HighestLeagueTier: LFrameValueUnknown,
    ShowChangeToonName: LFrameValueUnknown,
    UseStandardCoordinates: LFrameValueUnknown,


    MuteBgMusicWhilePlaying: LFrameValueUnknown,
    TeamId: LFrameValueUnknown,
    ObserverTeam: LFrameValueUnknown,
    IsArrangedTeam: LFrameValueUnknown,
    Rating: LFrameValueUnknown,
    IsPreviousSeason: LFrameValueUnknown,
    IsGrandmasterLadder: LFrameValueUnknown,
    TeamRecordId: LFrameValueUnknown,
    MessageArea: LFrameValueUnknown,
    TopToBottom: LFrameValueUnknown,
    HideClippedMessages: LFrameValueUnknown,
    FileTime: LFrameValueUnknown,
};
//nested framesA
LFrame.Frame = [LFrame]


export const SDesc = {
    "@": "Desc",
    locked: CString,
    DescFlags: LFrameValueUnknown,
    Include: [{path: A.Layout, requiredtoload: CWord}],
    Frame: [LFrame],
    StateGroup: [LStateGroup],
    Constant: [LConstant],
    Animation: [LAnimation]
}

export default {
    Frame: LFrame,
    Desc: SDesc,
}




